#	CYLINDRICAL
/gate/world/daughters/name cylindricalPET
/gate/world/daughters/insert cylinder
/gate/cylindricalPET/placement/setTranslation 0.0 0.0 0.0 cm
/gate/cylindricalPET/geometry/setRmax 90.0 mm
/gate/cylindricalPET/geometry/setRmin 80.0 mm
/gate/cylindricalPET/geometry/setHeight 100 mm
/gate/cylindricalPET/setMaterial Air
/gate/cylindricalPET/vis/forceWireframe
/gate/cylindricalPET/vis/setColor white

#	RSECTOR (detector modules)
/gate/cylindricalPET/daughters/name rsector
/gate/cylindricalPET/daughters/insert box
/gate/rsector/placement/setTranslation 85.0 0.0 0.0 mm
/gate/rsector/geometry/setXLength 10 mm
/gate/rsector/geometry/setYLength 50 mm
/gate/rsector/geometry/setZLength 50 mm
/gate/rsector/setMaterial Air
/gate/rsector/vis/setColor yellow


#	C R Y S T A L
/gate/rsector/daughters/name crystal
/gate/rsector/daughters/insert box
/gate/crystal/placement/setTranslation 0 0 0.0 mm
/gate/crystal/geometry/setXLength 10 mm
/gate/crystal/geometry/setYLength 1.0 mm
/gate/crystal/geometry/setZLength 1.0 mm
/gate/crystal/setMaterial Air
/gate/crystal/vis/setColor blue

#	LYSO
/gate/crystal/daughters/name LYSO
/gate/crystal/daughters/insert box
/gate/LYSO/placement/setTranslation 0 0 0.0 mm
/gate/LYSO/geometry/setXLength 10 mm
/gate/LYSO/geometry/setYLength 1.0 mm
/gate/LYSO/geometry/setZLength 1.0 mm
/gate/LYSO/setMaterial LYSO
/gate/LYSO/vis/forceSolid
/gate/LYSO/vis/setColor blue

# A T T A C H S Y S T E M
/gate/systems/cylindricalPET/rsector/attach rsector 
/gate/systems/cylindricalPET/crystal/attach crystal 
/gate/systems/cylindricalPET/layer0/attach LYSO 


#	R E P E A T    CRYSTAL
/gate/crystal/repeaters/insert cubicArray
/gate/crystal/cubicArray/setRepeatNumberX 1
/gate/crystal/cubicArray/setRepeatNumberY 48
/gate/crystal/cubicArray/setRepeatNumberZ 48
/gate/crystal/cubicArray/setRepeatVector 0.0 1.04 1.04 mm


#	R E P E A T    RSECTOR
/gate/rsector/repeaters/insert ring
#/gate/rsector/ring/setFirstAngle 11.25 deg
#/gate/rsector/ring/setFirstAngle 22.5 deg
#/gate/rsector/ring/setFirstAngle 33.75 deg
/gate/rsector/ring/setRepeatNumber 8


# A T T A C H L A Y E R SD 
/gate/LYSO/attachCrystalSD 

/gate/systems/cylindricalPET/describe




