/gate/source/addSource CYLINDER

/gate/source/CYLINDER/gps/particle gamma

/gate/source/CYLINDER/setActivity 100000. Bq
/gate/source/CYLINDER/setType backtoback

/gate/source/CYLINDER/gps/ene/type Mono
/gate/source/CYLINDER/gps/ene/mono 0.511 MeV

/gate/source/CYLINDER/gps/ang/type iso
/gate/source/CYLINDER/gps/ang/mintheta 0. deg
/gate/source/CYLINDER/gps/ang/maxtheta 180. deg
/gate/source/CYLINDER/gps/ang/minphi 0. deg
/gate/source/CYLINDER/gps/ang/maxphi 360. deg

/gate/source/CYLINDER/gps/type Volume

/gate/source/CYLINDER/gps/pos/shape Cylinder
/gate/source/CYLINDER/gps/pos/radius 0.5 mm
/gate/source/CYLINDER/gps/pos/halfz 25 mm



/gate/source/CYLINDER/gps/pos/centre 0. 0. 0. cm
