########################## 1.3 mm #######################

/gate/source/addSource F18LineSource0_0
/gate/source/F18LineSource0_0/setActivity 560606 Bq
/gate/source/F18LineSource0_0/setType backtoback
/gate/source/F18LineSource0_0/gps/particle gamma
/gate/source/F18LineSource0_0/gps/energytype Mono
/gate/source/F18LineSource0_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_0/gps/type Volume
/gate/source/F18LineSource0_0/gps/shape Cylinder
/gate/source/F18LineSource0_0/gps/halfz 10 mm
/gate/source/F18LineSource0_0/gps/angtype iso
/gate/source/F18LineSource0_0/gps/radius 1.1 mm
/gate/source/F18LineSource0_0/gps/centre 60.0 8.81051177665153 0 mm

/gate/source/addSource F18LineSource0_1
/gate/source/F18LineSource0_1/setActivity 560606 Bq
/gate/source/F18LineSource0_1/setType backtoback
/gate/source/F18LineSource0_1/gps/particle gamma
/gate/source/F18LineSource0_1/gps/energytype Mono
/gate/source/F18LineSource0_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_1/gps/type Volume
/gate/source/F18LineSource0_1/gps/shape Cylinder
/gate/source/F18LineSource0_1/gps/halfz 10 mm
/gate/source/F18LineSource0_1/gps/angtype iso
/gate/source/F18LineSource0_1/gps/radius 1.1 mm
/gate/source/F18LineSource0_1/gps/centre 57.8 12.621023553303061 0 mm

/gate/source/addSource F18LineSource0_2
/gate/source/F18LineSource0_2/setActivity 560606 Bq
/gate/source/F18LineSource0_2/setType backtoback
/gate/source/F18LineSource0_2/gps/particle gamma
/gate/source/F18LineSource0_2/gps/energytype Mono
/gate/source/F18LineSource0_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_2/gps/type Volume
/gate/source/F18LineSource0_2/gps/shape Cylinder
/gate/source/F18LineSource0_2/gps/halfz 10 mm
/gate/source/F18LineSource0_2/gps/angtype iso
/gate/source/F18LineSource0_2/gps/radius 1.1 mm
/gate/source/F18LineSource0_2/gps/centre 62.2 12.621023553303061 0 mm

/gate/source/addSource F18LineSource0_3
/gate/source/F18LineSource0_3/setActivity 560606 Bq
/gate/source/F18LineSource0_3/setType backtoback
/gate/source/F18LineSource0_3/gps/particle gamma
/gate/source/F18LineSource0_3/gps/energytype Mono
/gate/source/F18LineSource0_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_3/gps/type Volume
/gate/source/F18LineSource0_3/gps/shape Cylinder
/gate/source/F18LineSource0_3/gps/halfz 10 mm
/gate/source/F18LineSource0_3/gps/angtype iso
/gate/source/F18LineSource0_3/gps/radius 1.1 mm
/gate/source/F18LineSource0_3/gps/centre 55.6 16.431535329954592 0 mm

/gate/source/addSource F18LineSource0_4
/gate/source/F18LineSource0_4/setActivity 560606 Bq
/gate/source/F18LineSource0_4/setType backtoback
/gate/source/F18LineSource0_4/gps/particle gamma
/gate/source/F18LineSource0_4/gps/energytype Mono
/gate/source/F18LineSource0_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_4/gps/type Volume
/gate/source/F18LineSource0_4/gps/shape Cylinder
/gate/source/F18LineSource0_4/gps/halfz 10 mm
/gate/source/F18LineSource0_4/gps/angtype iso
/gate/source/F18LineSource0_4/gps/radius 1.1 mm
/gate/source/F18LineSource0_4/gps/centre 60.0 16.431535329954592 0 mm

/gate/source/addSource F18LineSource0_5
/gate/source/F18LineSource0_5/setActivity 560606 Bq
/gate/source/F18LineSource0_5/setType backtoback
/gate/source/F18LineSource0_5/gps/particle gamma
/gate/source/F18LineSource0_5/gps/energytype Mono
/gate/source/F18LineSource0_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_5/gps/type Volume
/gate/source/F18LineSource0_5/gps/shape Cylinder
/gate/source/F18LineSource0_5/gps/halfz 10 mm
/gate/source/F18LineSource0_5/gps/angtype iso
/gate/source/F18LineSource0_5/gps/radius 1.1 mm
/gate/source/F18LineSource0_5/gps/centre 64.4 16.431535329954592 0 mm

/gate/source/addSource F18LineSource0_6
/gate/source/F18LineSource0_6/setActivity 560606 Bq
/gate/source/F18LineSource0_6/setType backtoback
/gate/source/F18LineSource0_6/gps/particle gamma
/gate/source/F18LineSource0_6/gps/energytype Mono
/gate/source/F18LineSource0_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_6/gps/type Volume
/gate/source/F18LineSource0_6/gps/shape Cylinder
/gate/source/F18LineSource0_6/gps/halfz 10 mm
/gate/source/F18LineSource0_6/gps/angtype iso
/gate/source/F18LineSource0_6/gps/radius 1.1 mm
/gate/source/F18LineSource0_6/gps/centre 53.4 20.242047106606122 0 mm

/gate/source/addSource F18LineSource0_7
/gate/source/F18LineSource0_7/setActivity 560606 Bq
/gate/source/F18LineSource0_7/setType backtoback
/gate/source/F18LineSource0_7/gps/particle gamma
/gate/source/F18LineSource0_7/gps/energytype Mono
/gate/source/F18LineSource0_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_7/gps/type Volume
/gate/source/F18LineSource0_7/gps/shape Cylinder
/gate/source/F18LineSource0_7/gps/halfz 10 mm
/gate/source/F18LineSource0_7/gps/angtype iso
/gate/source/F18LineSource0_7/gps/radius 1.1 mm
/gate/source/F18LineSource0_7/gps/centre 57.8 20.242047106606122 0 mm

/gate/source/addSource F18LineSource0_8
/gate/source/F18LineSource0_8/setActivity 560606 Bq
/gate/source/F18LineSource0_8/setType backtoback
/gate/source/F18LineSource0_8/gps/particle gamma
/gate/source/F18LineSource0_8/gps/energytype Mono
/gate/source/F18LineSource0_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_8/gps/type Volume
/gate/source/F18LineSource0_8/gps/shape Cylinder
/gate/source/F18LineSource0_8/gps/halfz 10 mm
/gate/source/F18LineSource0_8/gps/angtype iso
/gate/source/F18LineSource0_8/gps/radius 1.1 mm
/gate/source/F18LineSource0_8/gps/centre 62.2 20.242047106606122 0 mm

/gate/source/addSource F18LineSource0_9
/gate/source/F18LineSource0_9/setActivity 560606 Bq
/gate/source/F18LineSource0_9/setType backtoback
/gate/source/F18LineSource0_9/gps/particle gamma
/gate/source/F18LineSource0_9/gps/energytype Mono
/gate/source/F18LineSource0_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_9/gps/type Volume
/gate/source/F18LineSource0_9/gps/shape Cylinder
/gate/source/F18LineSource0_9/gps/halfz 10 mm
/gate/source/F18LineSource0_9/gps/angtype iso
/gate/source/F18LineSource0_9/gps/radius 1.1 mm
/gate/source/F18LineSource0_9/gps/centre 66.6 20.242047106606122 0 mm

########################## 1.5 mm #######################

/gate/source/addSource F18LineSource1_0
/gate/source/F18LineSource1_0/setActivity 646853 Bq
/gate/source/F18LineSource1_0/setType backtoback
/gate/source/F18LineSource1_0/gps/particle gamma
/gate/source/F18LineSource1_0/gps/energytype Mono
/gate/source/F18LineSource1_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_0/gps/type Volume
/gate/source/F18LineSource1_0/gps/shape Cylinder
/gate/source/F18LineSource1_0/gps/halfz 10 mm
/gate/source/F18LineSource1_0/gps/angtype iso
/gate/source/F18LineSource1_0/gps/radius 1.2 mm
/gate/source/F18LineSource1_0/gps/centre 52.06987298107781 4.578460969082653 0 mm

/gate/source/addSource F18LineSource1_1
/gate/source/F18LineSource1_1/setActivity 646853 Bq
/gate/source/F18LineSource1_1/setType backtoback
/gate/source/F18LineSource1_1/gps/particle gamma
/gate/source/F18LineSource1_1/gps/energytype Mono
/gate/source/F18LineSource1_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_1/gps/type Volume
/gate/source/F18LineSource1_1/gps/shape Cylinder
/gate/source/F18LineSource1_1/gps/halfz 10 mm
/gate/source/F18LineSource1_1/gps/angtype iso
/gate/source/F18LineSource1_1/gps/radius 1.2 mm
/gate/source/F18LineSource1_1/gps/centre 47.26987298107781 4.578460969082654 0 mm

/gate/source/addSource F18LineSource1_2
/gate/source/F18LineSource1_2/setActivity 646853 Bq
/gate/source/F18LineSource1_2/setType backtoback
/gate/source/F18LineSource1_2/gps/particle gamma
/gate/source/F18LineSource1_2/gps/energytype Mono
/gate/source/F18LineSource1_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_2/gps/type Volume
/gate/source/F18LineSource1_2/gps/shape Cylinder
/gate/source/F18LineSource1_2/gps/halfz 10 mm
/gate/source/F18LineSource1_2/gps/angtype iso
/gate/source/F18LineSource1_2/gps/radius 1.2 mm
/gate/source/F18LineSource1_2/gps/centre 49.66987298107781 8.73538290724796 0 mm

/gate/source/addSource F18LineSource1_3
/gate/source/F18LineSource1_3/setActivity 646853 Bq
/gate/source/F18LineSource1_3/setType backtoback
/gate/source/F18LineSource1_3/gps/particle gamma
/gate/source/F18LineSource1_3/gps/energytype Mono
/gate/source/F18LineSource1_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_3/gps/type Volume
/gate/source/F18LineSource1_3/gps/shape Cylinder
/gate/source/F18LineSource1_3/gps/halfz 10 mm
/gate/source/F18LineSource1_3/gps/angtype iso
/gate/source/F18LineSource1_3/gps/radius 1.2 mm
/gate/source/F18LineSource1_3/gps/centre 42.469872981077806 4.578460969082655 0 mm

/gate/source/addSource F18LineSource1_4
/gate/source/F18LineSource1_4/setActivity 646853 Bq
/gate/source/F18LineSource1_4/setType backtoback
/gate/source/F18LineSource1_4/gps/particle gamma
/gate/source/F18LineSource1_4/gps/energytype Mono
/gate/source/F18LineSource1_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_4/gps/type Volume
/gate/source/F18LineSource1_4/gps/shape Cylinder
/gate/source/F18LineSource1_4/gps/halfz 10 mm
/gate/source/F18LineSource1_4/gps/angtype iso
/gate/source/F18LineSource1_4/gps/radius 1.2 mm
/gate/source/F18LineSource1_4/gps/centre 44.869872981077805 8.73538290724796 0 mm

/gate/source/addSource F18LineSource1_5
/gate/source/F18LineSource1_5/setActivity 646853 Bq
/gate/source/F18LineSource1_5/setType backtoback
/gate/source/F18LineSource1_5/gps/particle gamma
/gate/source/F18LineSource1_5/gps/energytype Mono
/gate/source/F18LineSource1_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_5/gps/type Volume
/gate/source/F18LineSource1_5/gps/shape Cylinder
/gate/source/F18LineSource1_5/gps/halfz 10 mm
/gate/source/F18LineSource1_5/gps/angtype iso
/gate/source/F18LineSource1_5/gps/radius 1.2 mm
/gate/source/F18LineSource1_5/gps/centre 47.26987298107781 12.892304845413264 0 mm

/gate/source/addSource F18LineSource1_6
/gate/source/F18LineSource1_6/setActivity 646853 Bq
/gate/source/F18LineSource1_6/setType backtoback
/gate/source/F18LineSource1_6/gps/particle gamma
/gate/source/F18LineSource1_6/gps/energytype Mono
/gate/source/F18LineSource1_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_6/gps/type Volume
/gate/source/F18LineSource1_6/gps/shape Cylinder
/gate/source/F18LineSource1_6/gps/halfz 10 mm
/gate/source/F18LineSource1_6/gps/angtype iso
/gate/source/F18LineSource1_6/gps/radius 1.2 mm
/gate/source/F18LineSource1_6/gps/centre 37.66987298107781 4.578460969082655 0 mm

/gate/source/addSource F18LineSource1_7
/gate/source/F18LineSource1_7/setActivity 646853 Bq
/gate/source/F18LineSource1_7/setType backtoback
/gate/source/F18LineSource1_7/gps/particle gamma
/gate/source/F18LineSource1_7/gps/energytype Mono
/gate/source/F18LineSource1_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_7/gps/type Volume
/gate/source/F18LineSource1_7/gps/shape Cylinder
/gate/source/F18LineSource1_7/gps/halfz 10 mm
/gate/source/F18LineSource1_7/gps/angtype iso
/gate/source/F18LineSource1_7/gps/radius 1.2 mm
/gate/source/F18LineSource1_7/gps/centre 40.06987298107781 8.73538290724796 0 mm

/gate/source/addSource F18LineSource1_8
/gate/source/F18LineSource1_8/setActivity 646853 Bq
/gate/source/F18LineSource1_8/setType backtoback
/gate/source/F18LineSource1_8/gps/particle gamma
/gate/source/F18LineSource1_8/gps/energytype Mono
/gate/source/F18LineSource1_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_8/gps/type Volume
/gate/source/F18LineSource1_8/gps/shape Cylinder
/gate/source/F18LineSource1_8/gps/halfz 10 mm
/gate/source/F18LineSource1_8/gps/angtype iso
/gate/source/F18LineSource1_8/gps/radius 1.2 mm
/gate/source/F18LineSource1_8/gps/centre 42.46987298107781 12.892304845413264 0 mm

/gate/source/addSource F18LineSource1_9
/gate/source/F18LineSource1_9/setActivity 646853 Bq
/gate/source/F18LineSource1_9/setType backtoback
/gate/source/F18LineSource1_9/gps/particle gamma
/gate/source/F18LineSource1_9/gps/energytype Mono
/gate/source/F18LineSource1_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_9/gps/type Volume
/gate/source/F18LineSource1_9/gps/shape Cylinder
/gate/source/F18LineSource1_9/gps/halfz 10 mm
/gate/source/F18LineSource1_9/gps/angtype iso
/gate/source/F18LineSource1_9/gps/radius 1.2 mm
/gate/source/F18LineSource1_9/gps/centre 44.86987298107781 17.04922678357857 0 mm

########################## 1.7 mm #######################

/gate/source/addSource F18LineSource2_0
/gate/source/F18LineSource2_0/setActivity 733100 Bq
/gate/source/F18LineSource2_0/setType backtoback
/gate/source/F18LineSource2_0/gps/particle gamma
/gate/source/F18LineSource2_0/gps/energytype Mono
/gate/source/F18LineSource2_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_0/gps/type Volume
/gate/source/F18LineSource2_0/gps/shape Cylinder
/gate/source/F18LineSource2_0/gps/halfz 10 mm
/gate/source/F18LineSource2_0/gps/angtype iso
/gate/source/F18LineSource2_0/gps/radius 1.3 mm
/gate/source/F18LineSource2_0/gps/centre 51.7698729810778 -4.751666049839539 0 mm

/gate/source/addSource F18LineSource2_1
/gate/source/F18LineSource2_1/setActivity 733100 Bq
/gate/source/F18LineSource2_1/setType backtoback
/gate/source/F18LineSource2_1/gps/particle gamma
/gate/source/F18LineSource2_1/gps/energytype Mono
/gate/source/F18LineSource2_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_1/gps/type Volume
/gate/source/F18LineSource2_1/gps/shape Cylinder
/gate/source/F18LineSource2_1/gps/halfz 10 mm
/gate/source/F18LineSource2_1/gps/angtype iso
/gate/source/F18LineSource2_1/gps/radius 1.3 mm
/gate/source/F18LineSource2_1/gps/centre 49.1698729810778 -9.254998149518618 0 mm

/gate/source/addSource F18LineSource2_2
/gate/source/F18LineSource2_2/setActivity 733100 Bq
/gate/source/F18LineSource2_2/setType backtoback
/gate/source/F18LineSource2_2/gps/particle gamma
/gate/source/F18LineSource2_2/gps/energytype Mono
/gate/source/F18LineSource2_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_2/gps/type Volume
/gate/source/F18LineSource2_2/gps/shape Cylinder
/gate/source/F18LineSource2_2/gps/halfz 10 mm
/gate/source/F18LineSource2_2/gps/angtype iso
/gate/source/F18LineSource2_2/gps/radius 1.3 mm
/gate/source/F18LineSource2_2/gps/centre 46.56987298107781 -4.751666049839537 0 mm

/gate/source/addSource F18LineSource2_3
/gate/source/F18LineSource2_3/setActivity 733100 Bq
/gate/source/F18LineSource2_3/setType backtoback
/gate/source/F18LineSource2_3/gps/particle gamma
/gate/source/F18LineSource2_3/gps/energytype Mono
/gate/source/F18LineSource2_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_3/gps/type Volume
/gate/source/F18LineSource2_3/gps/shape Cylinder
/gate/source/F18LineSource2_3/gps/halfz 10 mm
/gate/source/F18LineSource2_3/gps/angtype iso
/gate/source/F18LineSource2_3/gps/radius 1.3 mm
/gate/source/F18LineSource2_3/gps/centre 46.56987298107781 -13.758330249197698 0 mm

/gate/source/addSource F18LineSource2_4
/gate/source/F18LineSource2_4/setActivity 733100 Bq
/gate/source/F18LineSource2_4/setType backtoback
/gate/source/F18LineSource2_4/gps/particle gamma
/gate/source/F18LineSource2_4/gps/energytype Mono
/gate/source/F18LineSource2_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_4/gps/type Volume
/gate/source/F18LineSource2_4/gps/shape Cylinder
/gate/source/F18LineSource2_4/gps/halfz 10 mm
/gate/source/F18LineSource2_4/gps/angtype iso
/gate/source/F18LineSource2_4/gps/radius 1.3 mm
/gate/source/F18LineSource2_4/gps/centre 43.969872981077806 -9.254998149518617 0 mm

/gate/source/addSource F18LineSource2_5
/gate/source/F18LineSource2_5/setActivity 733100 Bq
/gate/source/F18LineSource2_5/setType backtoback
/gate/source/F18LineSource2_5/gps/particle gamma
/gate/source/F18LineSource2_5/gps/energytype Mono
/gate/source/F18LineSource2_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_5/gps/type Volume
/gate/source/F18LineSource2_5/gps/shape Cylinder
/gate/source/F18LineSource2_5/gps/halfz 10 mm
/gate/source/F18LineSource2_5/gps/angtype iso
/gate/source/F18LineSource2_5/gps/radius 1.3 mm
/gate/source/F18LineSource2_5/gps/centre 41.369872981077805 -4.751666049839535 0 mm

########################## 1.9 mm #######################

/gate/source/addSource F18LineSource3_0
/gate/source/F18LineSource3_0/setActivity 819347 Bq
/gate/source/F18LineSource3_0/setType backtoback
/gate/source/F18LineSource3_0/gps/particle gamma
/gate/source/F18LineSource3_0/gps/energytype Mono
/gate/source/F18LineSource3_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_0/gps/type Volume
/gate/source/F18LineSource3_0/gps/shape Cylinder
/gate/source/F18LineSource3_0/gps/halfz 10 mm
/gate/source/F18LineSource3_0/gps/angtype iso
/gate/source/F18LineSource3_0/gps/radius 1.4 mm
/gate/source/F18LineSource3_0/gps/centre 60.0 -9.849742261192855 0 mm

/gate/source/addSource F18LineSource3_1
/gate/source/F18LineSource3_1/setActivity 819347 Bq
/gate/source/F18LineSource3_1/setType backtoback
/gate/source/F18LineSource3_1/gps/particle gamma
/gate/source/F18LineSource3_1/gps/energytype Mono
/gate/source/F18LineSource3_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_1/gps/type Volume
/gate/source/F18LineSource3_1/gps/shape Cylinder
/gate/source/F18LineSource3_1/gps/halfz 10 mm
/gate/source/F18LineSource3_1/gps/angtype iso
/gate/source/F18LineSource3_1/gps/radius 1.4 mm
/gate/source/F18LineSource3_1/gps/centre 62.8 -14.699484522385712 0 mm

/gate/source/addSource F18LineSource3_2
/gate/source/F18LineSource3_2/setActivity 819347 Bq
/gate/source/F18LineSource3_2/setType backtoback
/gate/source/F18LineSource3_2/gps/particle gamma
/gate/source/F18LineSource3_2/gps/energytype Mono
/gate/source/F18LineSource3_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_2/gps/type Volume
/gate/source/F18LineSource3_2/gps/shape Cylinder
/gate/source/F18LineSource3_2/gps/halfz 10 mm
/gate/source/F18LineSource3_2/gps/angtype iso
/gate/source/F18LineSource3_2/gps/radius 1.4 mm
/gate/source/F18LineSource3_2/gps/centre 57.199999999999996 -14.699484522385712 0 mm

/gate/source/addSource F18LineSource3_3
/gate/source/F18LineSource3_3/setActivity 819347 Bq
/gate/source/F18LineSource3_3/setType backtoback
/gate/source/F18LineSource3_3/gps/particle gamma
/gate/source/F18LineSource3_3/gps/energytype Mono
/gate/source/F18LineSource3_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_3/gps/type Volume
/gate/source/F18LineSource3_3/gps/shape Cylinder
/gate/source/F18LineSource3_3/gps/halfz 10 mm
/gate/source/F18LineSource3_3/gps/angtype iso
/gate/source/F18LineSource3_3/gps/radius 1.4 mm
/gate/source/F18LineSource3_3/gps/centre 65.6 -19.54922678357857 0 mm

/gate/source/addSource F18LineSource3_4
/gate/source/F18LineSource3_4/setActivity 819347 Bq
/gate/source/F18LineSource3_4/setType backtoback
/gate/source/F18LineSource3_4/gps/particle gamma
/gate/source/F18LineSource3_4/gps/energytype Mono
/gate/source/F18LineSource3_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_4/gps/type Volume
/gate/source/F18LineSource3_4/gps/shape Cylinder
/gate/source/F18LineSource3_4/gps/halfz 10 mm
/gate/source/F18LineSource3_4/gps/angtype iso
/gate/source/F18LineSource3_4/gps/radius 1.4 mm
/gate/source/F18LineSource3_4/gps/centre 60.0 -19.54922678357857 0 mm

/gate/source/addSource F18LineSource3_5
/gate/source/F18LineSource3_5/setActivity 819347 Bq
/gate/source/F18LineSource3_5/setType backtoback
/gate/source/F18LineSource3_5/gps/particle gamma
/gate/source/F18LineSource3_5/gps/energytype Mono
/gate/source/F18LineSource3_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_5/gps/type Volume
/gate/source/F18LineSource3_5/gps/shape Cylinder
/gate/source/F18LineSource3_5/gps/halfz 10 mm
/gate/source/F18LineSource3_5/gps/angtype iso
/gate/source/F18LineSource3_5/gps/radius 1.4 mm
/gate/source/F18LineSource3_5/gps/centre 54.4 -19.54922678357857 0 mm

########################## 2.1 mm #######################

/gate/source/addSource F18LineSource4_0
/gate/source/F18LineSource4_0/setActivity 905594 Bq
/gate/source/F18LineSource4_0/setType backtoback
/gate/source/F18LineSource4_0/gps/particle gamma
/gate/source/F18LineSource4_0/gps/energytype Mono
/gate/source/F18LineSource4_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_0/gps/type Volume
/gate/source/F18LineSource4_0/gps/shape Cylinder
/gate/source/F18LineSource4_0/gps/halfz 10 mm
/gate/source/F18LineSource4_0/gps/angtype iso
/gate/source/F18LineSource4_0/gps/radius 1.5 mm
/gate/source/F18LineSource4_0/gps/centre 68.83012701892218 -5.0980762113533205 0 mm

/gate/source/addSource F18LineSource4_1
/gate/source/F18LineSource4_1/setActivity 905594 Bq
/gate/source/F18LineSource4_1/setType backtoback
/gate/source/F18LineSource4_1/gps/particle gamma
/gate/source/F18LineSource4_1/gps/energytype Mono
/gate/source/F18LineSource4_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_1/gps/type Volume
/gate/source/F18LineSource4_1/gps/shape Cylinder
/gate/source/F18LineSource4_1/gps/halfz 10 mm
/gate/source/F18LineSource4_1/gps/angtype iso
/gate/source/F18LineSource4_1/gps/radius 1.5 mm
/gate/source/F18LineSource4_1/gps/centre 74.83012701892218 -5.098076211353324 0 mm

/gate/source/addSource F18LineSource4_2
/gate/source/F18LineSource4_2/setActivity 905594 Bq
/gate/source/F18LineSource4_2/setType backtoback
/gate/source/F18LineSource4_2/gps/particle gamma
/gate/source/F18LineSource4_2/gps/energytype Mono
/gate/source/F18LineSource4_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_2/gps/type Volume
/gate/source/F18LineSource4_2/gps/shape Cylinder
/gate/source/F18LineSource4_2/gps/halfz 10 mm
/gate/source/F18LineSource4_2/gps/angtype iso
/gate/source/F18LineSource4_2/gps/radius 1.5 mm
/gate/source/F18LineSource4_2/gps/centre 71.83012701892218 -10.294228634059955 0 mm

/gate/source/addSource F18LineSource4_3
/gate/source/F18LineSource4_3/setActivity 905594 Bq
/gate/source/F18LineSource4_3/setType backtoback
/gate/source/F18LineSource4_3/gps/particle gamma
/gate/source/F18LineSource4_3/gps/energytype Mono
/gate/source/F18LineSource4_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_3/gps/type Volume
/gate/source/F18LineSource4_3/gps/shape Cylinder
/gate/source/F18LineSource4_3/gps/halfz 10 mm
/gate/source/F18LineSource4_3/gps/angtype iso
/gate/source/F18LineSource4_3/gps/radius 1.5 mm
/gate/source/F18LineSource4_3/gps/centre 80.83012701892218 -5.098076211353327 0 mm

/gate/source/addSource F18LineSource4_4
/gate/source/F18LineSource4_4/setActivity 905594 Bq
/gate/source/F18LineSource4_4/setType backtoback
/gate/source/F18LineSource4_4/gps/particle gamma
/gate/source/F18LineSource4_4/gps/energytype Mono
/gate/source/F18LineSource4_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_4/gps/type Volume
/gate/source/F18LineSource4_4/gps/shape Cylinder
/gate/source/F18LineSource4_4/gps/halfz 10 mm
/gate/source/F18LineSource4_4/gps/angtype iso
/gate/source/F18LineSource4_4/gps/radius 1.5 mm
/gate/source/F18LineSource4_4/gps/centre 77.83012701892218 -10.294228634059957 0 mm

/gate/source/addSource F18LineSource4_5
/gate/source/F18LineSource4_5/setActivity 905594 Bq
/gate/source/F18LineSource4_5/setType backtoback
/gate/source/F18LineSource4_5/gps/particle gamma
/gate/source/F18LineSource4_5/gps/energytype Mono
/gate/source/F18LineSource4_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_5/gps/type Volume
/gate/source/F18LineSource4_5/gps/shape Cylinder
/gate/source/F18LineSource4_5/gps/halfz 10 mm
/gate/source/F18LineSource4_5/gps/angtype iso
/gate/source/F18LineSource4_5/gps/radius 1.5 mm
/gate/source/F18LineSource4_5/gps/centre 74.83012701892218 -15.490381056766587 0 mm

########################## 2.3 mm #######################

/gate/source/addSource F18LineSource5_0
/gate/source/F18LineSource5_0/setActivity 1207459 Bq
/gate/source/F18LineSource5_0/setType backtoback
/gate/source/F18LineSource5_0/gps/particle gamma
/gate/source/F18LineSource5_0/gps/energytype Mono
/gate/source/F18LineSource5_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_0/gps/type Volume
/gate/source/F18LineSource5_0/gps/shape Cylinder
/gate/source/F18LineSource5_0/gps/halfz 10 mm
/gate/source/F18LineSource5_0/gps/angtype iso
/gate/source/F18LineSource5_0/gps/radius 1.6 mm
/gate/source/F18LineSource5_0/gps/centre 69.1301270189222 5.271281292110205 0 mm

/gate/source/addSource F18LineSource5_1
/gate/source/F18LineSource5_1/setActivity 1207459 Bq
/gate/source/F18LineSource5_1/setType backtoback
/gate/source/F18LineSource5_1/gps/particle gamma
/gate/source/F18LineSource5_1/gps/energytype Mono
/gate/source/F18LineSource5_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_1/gps/type Volume
/gate/source/F18LineSource5_1/gps/shape Cylinder
/gate/source/F18LineSource5_1/gps/halfz 10 mm
/gate/source/F18LineSource5_1/gps/angtype iso
/gate/source/F18LineSource5_1/gps/radius 1.6 mm
/gate/source/F18LineSource5_1/gps/centre 72.33012701892218 10.813843876330612 0 mm

/gate/source/addSource F18LineSource5_2
/gate/source/F18LineSource5_2/setActivity 1207459 Bq
/gate/source/F18LineSource5_2/setType backtoback
/gate/source/F18LineSource5_2/gps/particle gamma
/gate/source/F18LineSource5_2/gps/energytype Mono
/gate/source/F18LineSource5_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_2/gps/type Volume
/gate/source/F18LineSource5_2/gps/shape Cylinder
/gate/source/F18LineSource5_2/gps/halfz 10 mm
/gate/source/F18LineSource5_2/gps/angtype iso
/gate/source/F18LineSource5_2/gps/radius 1.6 mm
/gate/source/F18LineSource5_2/gps/centre 75.5301270189222 5.2712812921102055 0 mm

/gate/source/addSource F18LineSource5_3
/gate/source/F18LineSource5_3/setActivity 1207459 Bq
/gate/source/F18LineSource5_3/setType backtoback
/gate/source/F18LineSource5_3/gps/particle gamma
/gate/source/F18LineSource5_3/gps/energytype Mono
/gate/source/F18LineSource5_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_3/gps/type Volume
/gate/source/F18LineSource5_3/gps/shape Cylinder
/gate/source/F18LineSource5_3/gps/halfz 10 mm
/gate/source/F18LineSource5_3/gps/angtype iso
/gate/source/F18LineSource5_3/gps/radius 1.6 mm
/gate/source/F18LineSource5_3/gps/centre 75.53012701892219 16.35640646055102 0 mm

/gate/source/addSource F18LineSource5_4
/gate/source/F18LineSource5_4/setActivity 1207459 Bq
/gate/source/F18LineSource5_4/setType backtoback
/gate/source/F18LineSource5_4/gps/particle gamma
/gate/source/F18LineSource5_4/gps/energytype Mono
/gate/source/F18LineSource5_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_4/gps/type Volume
/gate/source/F18LineSource5_4/gps/shape Cylinder
/gate/source/F18LineSource5_4/gps/halfz 10 mm
/gate/source/F18LineSource5_4/gps/angtype iso
/gate/source/F18LineSource5_4/gps/radius 1.6 mm
/gate/source/F18LineSource5_4/gps/centre 78.73012701892219 10.813843876330614 0 mm

/gate/source/addSource F18LineSource5_5
/gate/source/F18LineSource5_5/setActivity 1207459 Bq
/gate/source/F18LineSource5_5/setType backtoback
/gate/source/F18LineSource5_5/gps/particle gamma
/gate/source/F18LineSource5_5/gps/energytype Mono
/gate/source/F18LineSource5_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_5/gps/type Volume
/gate/source/F18LineSource5_5/gps/shape Cylinder
/gate/source/F18LineSource5_5/gps/halfz 10 mm
/gate/source/F18LineSource5_5/gps/angtype iso
/gate/source/F18LineSource5_5/gps/radius 1.6 mm
/gate/source/F18LineSource5_5/gps/centre 81.93012701892219 5.271281292110206 0 mm

