/gate/source/addSource CylinderSource
/gate/source/CylinderSource/setActivity 0 Bq
/gate/source/CylinderSource/setType backtoback
/gate/source/CylinderSource/gps/particle gamma
/gate/source/CylinderSource/gps/energytype Mono
/gate/source/CylinderSource/gps/monoenergy 0.511 MeV
/gate/source/CylinderSource/gps/type Volume
/gate/source/CylinderSource/gps/shape Cylinder
/gate/source/CylinderSource/gps/radius 30 mm
/gate/source/CylinderSource/gps/halfz 40.0 mm
/gate/source/CylinderSource/gps/angtype iso
/gate/source/CylinderSource/gps/centre 0. 0. 0. mm

########################## 1.2 mm #######################

/gate/source/addSource F18LineSource0_0
/gate/source/F18LineSource0_0/setActivity 200000 Bq
/gate/source/F18LineSource0_0/setType backtoback
/gate/source/F18LineSource0_0/gps/particle gamma
/gate/source/F18LineSource0_0/gps/energytype Mono
/gate/source/F18LineSource0_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_0/gps/type Volume
/gate/source/F18LineSource0_0/gps/shape Cylinder
/gate/source/F18LineSource0_0/gps/halfz 40.0 mm
/gate/source/F18LineSource0_0/gps/angtype iso
/gate/source/F18LineSource0_0/gps/radius 0.9 mm
/gate/source/F18LineSource0_0/gps/centre 0.0 8.11769145362398 0.000000 mm

/gate/source/addSource F18LineSource0_1
/gate/source/F18LineSource0_1/setActivity 200000 Bq
/gate/source/F18LineSource0_1/setType backtoback
/gate/source/F18LineSource0_1/gps/particle gamma
/gate/source/F18LineSource0_1/gps/energytype Mono
/gate/source/F18LineSource0_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_1/gps/type Volume
/gate/source/F18LineSource0_1/gps/shape Cylinder
/gate/source/F18LineSource0_1/gps/halfz 40.0 mm
/gate/source/F18LineSource0_1/gps/angtype iso
/gate/source/F18LineSource0_1/gps/radius 0.9 mm
/gate/source/F18LineSource0_1/gps/centre -1.8 11.235382907247958 0.000000 mm

/gate/source/addSource F18LineSource0_2
/gate/source/F18LineSource0_2/setActivity 200000 Bq
/gate/source/F18LineSource0_2/setType backtoback
/gate/source/F18LineSource0_2/gps/particle gamma
/gate/source/F18LineSource0_2/gps/energytype Mono
/gate/source/F18LineSource0_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_2/gps/type Volume
/gate/source/F18LineSource0_2/gps/shape Cylinder
/gate/source/F18LineSource0_2/gps/halfz 40.0 mm
/gate/source/F18LineSource0_2/gps/angtype iso
/gate/source/F18LineSource0_2/gps/radius 0.9 mm
/gate/source/F18LineSource0_2/gps/centre 1.8 11.235382907247958 0.000000 mm

/gate/source/addSource F18LineSource0_3
/gate/source/F18LineSource0_3/setActivity 200000 Bq
/gate/source/F18LineSource0_3/setType backtoback
/gate/source/F18LineSource0_3/gps/particle gamma
/gate/source/F18LineSource0_3/gps/energytype Mono
/gate/source/F18LineSource0_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_3/gps/type Volume
/gate/source/F18LineSource0_3/gps/shape Cylinder
/gate/source/F18LineSource0_3/gps/halfz 40.0 mm
/gate/source/F18LineSource0_3/gps/angtype iso
/gate/source/F18LineSource0_3/gps/radius 0.9 mm
/gate/source/F18LineSource0_3/gps/centre -3.6 14.353074360871936 0.000000 mm

/gate/source/addSource F18LineSource0_4
/gate/source/F18LineSource0_4/setActivity 200000 Bq
/gate/source/F18LineSource0_4/setType backtoback
/gate/source/F18LineSource0_4/gps/particle gamma
/gate/source/F18LineSource0_4/gps/energytype Mono
/gate/source/F18LineSource0_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_4/gps/type Volume
/gate/source/F18LineSource0_4/gps/shape Cylinder
/gate/source/F18LineSource0_4/gps/halfz 40.0 mm
/gate/source/F18LineSource0_4/gps/angtype iso
/gate/source/F18LineSource0_4/gps/radius 0.9 mm
/gate/source/F18LineSource0_4/gps/centre 0.0 14.353074360871936 0.000000 mm

/gate/source/addSource F18LineSource0_5
/gate/source/F18LineSource0_5/setActivity 200000 Bq
/gate/source/F18LineSource0_5/setType backtoback
/gate/source/F18LineSource0_5/gps/particle gamma
/gate/source/F18LineSource0_5/gps/energytype Mono
/gate/source/F18LineSource0_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_5/gps/type Volume
/gate/source/F18LineSource0_5/gps/shape Cylinder
/gate/source/F18LineSource0_5/gps/halfz 40.0 mm
/gate/source/F18LineSource0_5/gps/angtype iso
/gate/source/F18LineSource0_5/gps/radius 0.9 mm
/gate/source/F18LineSource0_5/gps/centre 3.6 14.353074360871936 0.000000 mm

/gate/source/addSource F18LineSource0_6
/gate/source/F18LineSource0_6/setActivity 200000 Bq
/gate/source/F18LineSource0_6/setType backtoback
/gate/source/F18LineSource0_6/gps/particle gamma
/gate/source/F18LineSource0_6/gps/energytype Mono
/gate/source/F18LineSource0_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_6/gps/type Volume
/gate/source/F18LineSource0_6/gps/shape Cylinder
/gate/source/F18LineSource0_6/gps/halfz 40.0 mm
/gate/source/F18LineSource0_6/gps/angtype iso
/gate/source/F18LineSource0_6/gps/radius 0.9 mm
/gate/source/F18LineSource0_6/gps/centre -5.4 17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource0_7
/gate/source/F18LineSource0_7/setActivity 200000 Bq
/gate/source/F18LineSource0_7/setType backtoback
/gate/source/F18LineSource0_7/gps/particle gamma
/gate/source/F18LineSource0_7/gps/energytype Mono
/gate/source/F18LineSource0_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_7/gps/type Volume
/gate/source/F18LineSource0_7/gps/shape Cylinder
/gate/source/F18LineSource0_7/gps/halfz 40.0 mm
/gate/source/F18LineSource0_7/gps/angtype iso
/gate/source/F18LineSource0_7/gps/radius 0.9 mm
/gate/source/F18LineSource0_7/gps/centre -1.8000000000000003 17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource0_8
/gate/source/F18LineSource0_8/setActivity 200000 Bq
/gate/source/F18LineSource0_8/setType backtoback
/gate/source/F18LineSource0_8/gps/particle gamma
/gate/source/F18LineSource0_8/gps/energytype Mono
/gate/source/F18LineSource0_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_8/gps/type Volume
/gate/source/F18LineSource0_8/gps/shape Cylinder
/gate/source/F18LineSource0_8/gps/halfz 40.0 mm
/gate/source/F18LineSource0_8/gps/angtype iso
/gate/source/F18LineSource0_8/gps/radius 0.9 mm
/gate/source/F18LineSource0_8/gps/centre 1.7999999999999998 17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource0_9
/gate/source/F18LineSource0_9/setActivity 200000 Bq
/gate/source/F18LineSource0_9/setType backtoback
/gate/source/F18LineSource0_9/gps/particle gamma
/gate/source/F18LineSource0_9/gps/energytype Mono
/gate/source/F18LineSource0_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_9/gps/type Volume
/gate/source/F18LineSource0_9/gps/shape Cylinder
/gate/source/F18LineSource0_9/gps/halfz 40.0 mm
/gate/source/F18LineSource0_9/gps/angtype iso
/gate/source/F18LineSource0_9/gps/radius 0.9 mm
/gate/source/F18LineSource0_9/gps/centre 5.4 17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource0_10
/gate/source/F18LineSource0_10/setActivity 200000 Bq
/gate/source/F18LineSource0_10/setType backtoback
/gate/source/F18LineSource0_10/gps/particle gamma
/gate/source/F18LineSource0_10/gps/energytype Mono
/gate/source/F18LineSource0_10/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_10/gps/type Volume
/gate/source/F18LineSource0_10/gps/shape Cylinder
/gate/source/F18LineSource0_10/gps/halfz 40.0 mm
/gate/source/F18LineSource0_10/gps/angtype iso
/gate/source/F18LineSource0_10/gps/radius 0.9 mm
/gate/source/F18LineSource0_10/gps/centre -7.2 20.588457268119896 0.000000 mm

/gate/source/addSource F18LineSource0_11
/gate/source/F18LineSource0_11/setActivity 200000 Bq
/gate/source/F18LineSource0_11/setType backtoback
/gate/source/F18LineSource0_11/gps/particle gamma
/gate/source/F18LineSource0_11/gps/energytype Mono
/gate/source/F18LineSource0_11/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_11/gps/type Volume
/gate/source/F18LineSource0_11/gps/shape Cylinder
/gate/source/F18LineSource0_11/gps/halfz 40.0 mm
/gate/source/F18LineSource0_11/gps/angtype iso
/gate/source/F18LineSource0_11/gps/radius 0.9 mm
/gate/source/F18LineSource0_11/gps/centre -3.6 20.588457268119896 0.000000 mm

/gate/source/addSource F18LineSource0_12
/gate/source/F18LineSource0_12/setActivity 200000 Bq
/gate/source/F18LineSource0_12/setType backtoback
/gate/source/F18LineSource0_12/gps/particle gamma
/gate/source/F18LineSource0_12/gps/energytype Mono
/gate/source/F18LineSource0_12/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_12/gps/type Volume
/gate/source/F18LineSource0_12/gps/shape Cylinder
/gate/source/F18LineSource0_12/gps/halfz 40.0 mm
/gate/source/F18LineSource0_12/gps/angtype iso
/gate/source/F18LineSource0_12/gps/radius 0.9 mm
/gate/source/F18LineSource0_12/gps/centre 0.0 20.588457268119896 0.000000 mm

/gate/source/addSource F18LineSource0_13
/gate/source/F18LineSource0_13/setActivity 200000 Bq
/gate/source/F18LineSource0_13/setType backtoback
/gate/source/F18LineSource0_13/gps/particle gamma
/gate/source/F18LineSource0_13/gps/energytype Mono
/gate/source/F18LineSource0_13/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_13/gps/type Volume
/gate/source/F18LineSource0_13/gps/shape Cylinder
/gate/source/F18LineSource0_13/gps/halfz 40.0 mm
/gate/source/F18LineSource0_13/gps/angtype iso
/gate/source/F18LineSource0_13/gps/radius 0.9 mm
/gate/source/F18LineSource0_13/gps/centre 3.6000000000000005 20.588457268119896 0.000000 mm

/gate/source/addSource F18LineSource0_14
/gate/source/F18LineSource0_14/setActivity 200000 Bq
/gate/source/F18LineSource0_14/setType backtoback
/gate/source/F18LineSource0_14/gps/particle gamma
/gate/source/F18LineSource0_14/gps/energytype Mono
/gate/source/F18LineSource0_14/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource0_14/gps/type Volume
/gate/source/F18LineSource0_14/gps/shape Cylinder
/gate/source/F18LineSource0_14/gps/halfz 40.0 mm
/gate/source/F18LineSource0_14/gps/angtype iso
/gate/source/F18LineSource0_14/gps/radius 0.9 mm
/gate/source/F18LineSource0_14/gps/centre 7.2 20.588457268119896 0.000000 mm

########################## 1.4 mm #######################

/gate/source/addSource F18LineSource1_0
/gate/source/F18LineSource1_0/setActivity 200000 Bq
/gate/source/F18LineSource1_0/setType backtoback
/gate/source/F18LineSource1_0/gps/particle gamma
/gate/source/F18LineSource1_0/gps/energytype Mono
/gate/source/F18LineSource1_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_0/gps/type Volume
/gate/source/F18LineSource1_0/gps/shape Cylinder
/gate/source/F18LineSource1_0/gps/halfz 40.0 mm
/gate/source/F18LineSource1_0/gps/angtype iso
/gate/source/F18LineSource1_0/gps/radius 1.0 mm
/gate/source/F18LineSource1_0/gps/centre -7.330127018922192 4.232050807568878 0.000000 mm

/gate/source/addSource F18LineSource1_1
/gate/source/F18LineSource1_1/setActivity 200000 Bq
/gate/source/F18LineSource1_1/setType backtoback
/gate/source/F18LineSource1_1/gps/particle gamma
/gate/source/F18LineSource1_1/gps/energytype Mono
/gate/source/F18LineSource1_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_1/gps/type Volume
/gate/source/F18LineSource1_1/gps/shape Cylinder
/gate/source/F18LineSource1_1/gps/halfz 40.0 mm
/gate/source/F18LineSource1_1/gps/angtype iso
/gate/source/F18LineSource1_1/gps/radius 1.0 mm
/gate/source/F18LineSource1_1/gps/centre -11.330127018922193 4.2320508075688785 0.000000 mm

/gate/source/addSource F18LineSource1_2
/gate/source/F18LineSource1_2/setActivity 200000 Bq
/gate/source/F18LineSource1_2/setType backtoback
/gate/source/F18LineSource1_2/gps/particle gamma
/gate/source/F18LineSource1_2/gps/energytype Mono
/gate/source/F18LineSource1_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_2/gps/type Volume
/gate/source/F18LineSource1_2/gps/shape Cylinder
/gate/source/F18LineSource1_2/gps/halfz 40.0 mm
/gate/source/F18LineSource1_2/gps/angtype iso
/gate/source/F18LineSource1_2/gps/radius 1.0 mm
/gate/source/F18LineSource1_2/gps/centre -9.330127018922193 7.696152422706632 0.000000 mm

/gate/source/addSource F18LineSource1_3
/gate/source/F18LineSource1_3/setActivity 200000 Bq
/gate/source/F18LineSource1_3/setType backtoback
/gate/source/F18LineSource1_3/gps/particle gamma
/gate/source/F18LineSource1_3/gps/energytype Mono
/gate/source/F18LineSource1_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_3/gps/type Volume
/gate/source/F18LineSource1_3/gps/shape Cylinder
/gate/source/F18LineSource1_3/gps/halfz 40.0 mm
/gate/source/F18LineSource1_3/gps/angtype iso
/gate/source/F18LineSource1_3/gps/radius 1.0 mm
/gate/source/F18LineSource1_3/gps/centre -15.330127018922193 4.232050807568879 0.000000 mm

/gate/source/addSource F18LineSource1_4
/gate/source/F18LineSource1_4/setActivity 200000 Bq
/gate/source/F18LineSource1_4/setType backtoback
/gate/source/F18LineSource1_4/gps/particle gamma
/gate/source/F18LineSource1_4/gps/energytype Mono
/gate/source/F18LineSource1_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_4/gps/type Volume
/gate/source/F18LineSource1_4/gps/shape Cylinder
/gate/source/F18LineSource1_4/gps/halfz 40.0 mm
/gate/source/F18LineSource1_4/gps/angtype iso
/gate/source/F18LineSource1_4/gps/radius 1.0 mm
/gate/source/F18LineSource1_4/gps/centre -13.330127018922193 7.696152422706634 0.000000 mm

/gate/source/addSource F18LineSource1_5
/gate/source/F18LineSource1_5/setActivity 200000 Bq
/gate/source/F18LineSource1_5/setType backtoback
/gate/source/F18LineSource1_5/gps/particle gamma
/gate/source/F18LineSource1_5/gps/energytype Mono
/gate/source/F18LineSource1_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_5/gps/type Volume
/gate/source/F18LineSource1_5/gps/shape Cylinder
/gate/source/F18LineSource1_5/gps/halfz 40.0 mm
/gate/source/F18LineSource1_5/gps/angtype iso
/gate/source/F18LineSource1_5/gps/radius 1.0 mm
/gate/source/F18LineSource1_5/gps/centre -11.330127018922193 11.160254037844389 0.000000 mm

/gate/source/addSource F18LineSource1_6
/gate/source/F18LineSource1_6/setActivity 200000 Bq
/gate/source/F18LineSource1_6/setType backtoback
/gate/source/F18LineSource1_6/gps/particle gamma
/gate/source/F18LineSource1_6/gps/energytype Mono
/gate/source/F18LineSource1_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_6/gps/type Volume
/gate/source/F18LineSource1_6/gps/shape Cylinder
/gate/source/F18LineSource1_6/gps/halfz 40.0 mm
/gate/source/F18LineSource1_6/gps/angtype iso
/gate/source/F18LineSource1_6/gps/radius 1.0 mm
/gate/source/F18LineSource1_6/gps/centre -19.33012701892219 4.2320508075688785 0.000000 mm

/gate/source/addSource F18LineSource1_7
/gate/source/F18LineSource1_7/setActivity 200000 Bq
/gate/source/F18LineSource1_7/setType backtoback
/gate/source/F18LineSource1_7/gps/particle gamma
/gate/source/F18LineSource1_7/gps/energytype Mono
/gate/source/F18LineSource1_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_7/gps/type Volume
/gate/source/F18LineSource1_7/gps/shape Cylinder
/gate/source/F18LineSource1_7/gps/halfz 40.0 mm
/gate/source/F18LineSource1_7/gps/angtype iso
/gate/source/F18LineSource1_7/gps/radius 1.0 mm
/gate/source/F18LineSource1_7/gps/centre -17.33012701892219 7.696152422706634 0.000000 mm

/gate/source/addSource F18LineSource1_8
/gate/source/F18LineSource1_8/setActivity 200000 Bq
/gate/source/F18LineSource1_8/setType backtoback
/gate/source/F18LineSource1_8/gps/particle gamma
/gate/source/F18LineSource1_8/gps/energytype Mono
/gate/source/F18LineSource1_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_8/gps/type Volume
/gate/source/F18LineSource1_8/gps/shape Cylinder
/gate/source/F18LineSource1_8/gps/halfz 40.0 mm
/gate/source/F18LineSource1_8/gps/angtype iso
/gate/source/F18LineSource1_8/gps/radius 1.0 mm
/gate/source/F18LineSource1_8/gps/centre -15.330127018922191 11.160254037844387 0.000000 mm

/gate/source/addSource F18LineSource1_9
/gate/source/F18LineSource1_9/setActivity 200000 Bq
/gate/source/F18LineSource1_9/setType backtoback
/gate/source/F18LineSource1_9/gps/particle gamma
/gate/source/F18LineSource1_9/gps/energytype Mono
/gate/source/F18LineSource1_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_9/gps/type Volume
/gate/source/F18LineSource1_9/gps/shape Cylinder
/gate/source/F18LineSource1_9/gps/halfz 40.0 mm
/gate/source/F18LineSource1_9/gps/angtype iso
/gate/source/F18LineSource1_9/gps/radius 1.0 mm
/gate/source/F18LineSource1_9/gps/centre -13.330127018922191 14.624355652982143 0.000000 mm

/gate/source/addSource F18LineSource1_10
/gate/source/F18LineSource1_10/setActivity 200000 Bq
/gate/source/F18LineSource1_10/setType backtoback
/gate/source/F18LineSource1_10/gps/particle gamma
/gate/source/F18LineSource1_10/gps/energytype Mono
/gate/source/F18LineSource1_10/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_10/gps/type Volume
/gate/source/F18LineSource1_10/gps/shape Cylinder
/gate/source/F18LineSource1_10/gps/halfz 40.0 mm
/gate/source/F18LineSource1_10/gps/angtype iso
/gate/source/F18LineSource1_10/gps/radius 1.0 mm
/gate/source/F18LineSource1_10/gps/centre -23.33012701892219 4.2320508075688785 0.000000 mm

/gate/source/addSource F18LineSource1_11
/gate/source/F18LineSource1_11/setActivity 200000 Bq
/gate/source/F18LineSource1_11/setType backtoback
/gate/source/F18LineSource1_11/gps/particle gamma
/gate/source/F18LineSource1_11/gps/energytype Mono
/gate/source/F18LineSource1_11/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_11/gps/type Volume
/gate/source/F18LineSource1_11/gps/shape Cylinder
/gate/source/F18LineSource1_11/gps/halfz 40.0 mm
/gate/source/F18LineSource1_11/gps/angtype iso
/gate/source/F18LineSource1_11/gps/radius 1.0 mm
/gate/source/F18LineSource1_11/gps/centre -21.33012701892219 7.696152422706633 0.000000 mm

/gate/source/addSource F18LineSource1_12
/gate/source/F18LineSource1_12/setActivity 200000 Bq
/gate/source/F18LineSource1_12/setType backtoback
/gate/source/F18LineSource1_12/gps/particle gamma
/gate/source/F18LineSource1_12/gps/energytype Mono
/gate/source/F18LineSource1_12/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_12/gps/type Volume
/gate/source/F18LineSource1_12/gps/shape Cylinder
/gate/source/F18LineSource1_12/gps/halfz 40.0 mm
/gate/source/F18LineSource1_12/gps/angtype iso
/gate/source/F18LineSource1_12/gps/radius 1.0 mm
/gate/source/F18LineSource1_12/gps/centre -19.33012701892219 11.160254037844387 0.000000 mm

/gate/source/addSource F18LineSource1_13
/gate/source/F18LineSource1_13/setActivity 200000 Bq
/gate/source/F18LineSource1_13/setType backtoback
/gate/source/F18LineSource1_13/gps/particle gamma
/gate/source/F18LineSource1_13/gps/energytype Mono
/gate/source/F18LineSource1_13/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_13/gps/type Volume
/gate/source/F18LineSource1_13/gps/shape Cylinder
/gate/source/F18LineSource1_13/gps/halfz 40.0 mm
/gate/source/F18LineSource1_13/gps/angtype iso
/gate/source/F18LineSource1_13/gps/radius 1.0 mm
/gate/source/F18LineSource1_13/gps/centre -17.33012701892219 14.624355652982143 0.000000 mm

/gate/source/addSource F18LineSource1_14
/gate/source/F18LineSource1_14/setActivity 200000 Bq
/gate/source/F18LineSource1_14/setType backtoback
/gate/source/F18LineSource1_14/gps/particle gamma
/gate/source/F18LineSource1_14/gps/energytype Mono
/gate/source/F18LineSource1_14/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource1_14/gps/type Volume
/gate/source/F18LineSource1_14/gps/shape Cylinder
/gate/source/F18LineSource1_14/gps/halfz 40.0 mm
/gate/source/F18LineSource1_14/gps/angtype iso
/gate/source/F18LineSource1_14/gps/radius 1.0 mm
/gate/source/F18LineSource1_14/gps/centre -15.330127018922191 18.088457268119896 0.000000 mm

########################## 1.6 mm #######################

/gate/source/addSource F18LineSource2_0
/gate/source/F18LineSource2_0/setActivity 200000 Bq
/gate/source/F18LineSource2_0/setType backtoback
/gate/source/F18LineSource2_0/gps/particle gamma
/gate/source/F18LineSource2_0/gps/energytype Mono
/gate/source/F18LineSource2_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_0/gps/type Volume
/gate/source/F18LineSource2_0/gps/shape Cylinder
/gate/source/F18LineSource2_0/gps/halfz 40.0 mm
/gate/source/F18LineSource2_0/gps/angtype iso
/gate/source/F18LineSource2_0/gps/radius 1.1 mm
/gate/source/F18LineSource2_0/gps/centre -7.630127018922194 -4.4052558883257635 0.000000 mm

/gate/source/addSource F18LineSource2_1
/gate/source/F18LineSource2_1/setActivity 200000 Bq
/gate/source/F18LineSource2_1/setType backtoback
/gate/source/F18LineSource2_1/gps/particle gamma
/gate/source/F18LineSource2_1/gps/energytype Mono
/gate/source/F18LineSource2_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_1/gps/type Volume
/gate/source/F18LineSource2_1/gps/shape Cylinder
/gate/source/F18LineSource2_1/gps/halfz 40.0 mm
/gate/source/F18LineSource2_1/gps/angtype iso
/gate/source/F18LineSource2_1/gps/radius 1.1 mm
/gate/source/F18LineSource2_1/gps/centre -9.830127018922195 -8.215767664977294 0.000000 mm

/gate/source/addSource F18LineSource2_2
/gate/source/F18LineSource2_2/setActivity 200000 Bq
/gate/source/F18LineSource2_2/setType backtoback
/gate/source/F18LineSource2_2/gps/particle gamma
/gate/source/F18LineSource2_2/gps/energytype Mono
/gate/source/F18LineSource2_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_2/gps/type Volume
/gate/source/F18LineSource2_2/gps/shape Cylinder
/gate/source/F18LineSource2_2/gps/halfz 40.0 mm
/gate/source/F18LineSource2_2/gps/angtype iso
/gate/source/F18LineSource2_2/gps/radius 1.1 mm
/gate/source/F18LineSource2_2/gps/centre -12.030127018922194 -4.4052558883257635 0.000000 mm

/gate/source/addSource F18LineSource2_3
/gate/source/F18LineSource2_3/setActivity 200000 Bq
/gate/source/F18LineSource2_3/setType backtoback
/gate/source/F18LineSource2_3/gps/particle gamma
/gate/source/F18LineSource2_3/gps/energytype Mono
/gate/source/F18LineSource2_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_3/gps/type Volume
/gate/source/F18LineSource2_3/gps/shape Cylinder
/gate/source/F18LineSource2_3/gps/halfz 40.0 mm
/gate/source/F18LineSource2_3/gps/angtype iso
/gate/source/F18LineSource2_3/gps/radius 1.1 mm
/gate/source/F18LineSource2_3/gps/centre -12.030127018922196 -12.026279441628823 0.000000 mm

/gate/source/addSource F18LineSource2_4
/gate/source/F18LineSource2_4/setActivity 200000 Bq
/gate/source/F18LineSource2_4/setType backtoback
/gate/source/F18LineSource2_4/gps/particle gamma
/gate/source/F18LineSource2_4/gps/energytype Mono
/gate/source/F18LineSource2_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_4/gps/type Volume
/gate/source/F18LineSource2_4/gps/shape Cylinder
/gate/source/F18LineSource2_4/gps/halfz 40.0 mm
/gate/source/F18LineSource2_4/gps/angtype iso
/gate/source/F18LineSource2_4/gps/radius 1.1 mm
/gate/source/F18LineSource2_4/gps/centre -14.230127018922195 -8.215767664977292 0.000000 mm

/gate/source/addSource F18LineSource2_5
/gate/source/F18LineSource2_5/setActivity 200000 Bq
/gate/source/F18LineSource2_5/setType backtoback
/gate/source/F18LineSource2_5/gps/particle gamma
/gate/source/F18LineSource2_5/gps/energytype Mono
/gate/source/F18LineSource2_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_5/gps/type Volume
/gate/source/F18LineSource2_5/gps/shape Cylinder
/gate/source/F18LineSource2_5/gps/halfz 40.0 mm
/gate/source/F18LineSource2_5/gps/angtype iso
/gate/source/F18LineSource2_5/gps/radius 1.1 mm
/gate/source/F18LineSource2_5/gps/centre -16.430127018922192 -4.405255888325762 0.000000 mm

/gate/source/addSource F18LineSource2_6
/gate/source/F18LineSource2_6/setActivity 200000 Bq
/gate/source/F18LineSource2_6/setType backtoback
/gate/source/F18LineSource2_6/gps/particle gamma
/gate/source/F18LineSource2_6/gps/energytype Mono
/gate/source/F18LineSource2_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_6/gps/type Volume
/gate/source/F18LineSource2_6/gps/shape Cylinder
/gate/source/F18LineSource2_6/gps/halfz 40.0 mm
/gate/source/F18LineSource2_6/gps/angtype iso
/gate/source/F18LineSource2_6/gps/radius 1.1 mm
/gate/source/F18LineSource2_6/gps/centre -14.230127018922198 -15.836791218280354 0.000000 mm

/gate/source/addSource F18LineSource2_7
/gate/source/F18LineSource2_7/setActivity 200000 Bq
/gate/source/F18LineSource2_7/setType backtoback
/gate/source/F18LineSource2_7/gps/particle gamma
/gate/source/F18LineSource2_7/gps/energytype Mono
/gate/source/F18LineSource2_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_7/gps/type Volume
/gate/source/F18LineSource2_7/gps/shape Cylinder
/gate/source/F18LineSource2_7/gps/halfz 40.0 mm
/gate/source/F18LineSource2_7/gps/angtype iso
/gate/source/F18LineSource2_7/gps/radius 1.1 mm
/gate/source/F18LineSource2_7/gps/centre -16.4301270189222 -12.026279441628823 0.000000 mm

/gate/source/addSource F18LineSource2_8
/gate/source/F18LineSource2_8/setActivity 200000 Bq
/gate/source/F18LineSource2_8/setType backtoback
/gate/source/F18LineSource2_8/gps/particle gamma
/gate/source/F18LineSource2_8/gps/energytype Mono
/gate/source/F18LineSource2_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_8/gps/type Volume
/gate/source/F18LineSource2_8/gps/shape Cylinder
/gate/source/F18LineSource2_8/gps/halfz 40.0 mm
/gate/source/F18LineSource2_8/gps/angtype iso
/gate/source/F18LineSource2_8/gps/radius 1.1 mm
/gate/source/F18LineSource2_8/gps/centre -18.630127018922195 -8.215767664977292 0.000000 mm

/gate/source/addSource F18LineSource2_9
/gate/source/F18LineSource2_9/setActivity 200000 Bq
/gate/source/F18LineSource2_9/setType backtoback
/gate/source/F18LineSource2_9/gps/particle gamma
/gate/source/F18LineSource2_9/gps/energytype Mono
/gate/source/F18LineSource2_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_9/gps/type Volume
/gate/source/F18LineSource2_9/gps/shape Cylinder
/gate/source/F18LineSource2_9/gps/halfz 40.0 mm
/gate/source/F18LineSource2_9/gps/angtype iso
/gate/source/F18LineSource2_9/gps/radius 1.1 mm
/gate/source/F18LineSource2_9/gps/centre -20.830127018922198 -4.405255888325762 0.000000 mm

/gate/source/addSource F18LineSource2_10
/gate/source/F18LineSource2_10/setActivity 200000 Bq
/gate/source/F18LineSource2_10/setType backtoback
/gate/source/F18LineSource2_10/gps/particle gamma
/gate/source/F18LineSource2_10/gps/energytype Mono
/gate/source/F18LineSource2_10/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_10/gps/type Volume
/gate/source/F18LineSource2_10/gps/shape Cylinder
/gate/source/F18LineSource2_10/gps/halfz 40.0 mm
/gate/source/F18LineSource2_10/gps/angtype iso
/gate/source/F18LineSource2_10/gps/radius 1.1 mm
/gate/source/F18LineSource2_10/gps/centre -16.430127018922196 -19.647302994931884 0.000000 mm

/gate/source/addSource F18LineSource2_11
/gate/source/F18LineSource2_11/setActivity 200000 Bq
/gate/source/F18LineSource2_11/setType backtoback
/gate/source/F18LineSource2_11/gps/particle gamma
/gate/source/F18LineSource2_11/gps/energytype Mono
/gate/source/F18LineSource2_11/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_11/gps/type Volume
/gate/source/F18LineSource2_11/gps/shape Cylinder
/gate/source/F18LineSource2_11/gps/halfz 40.0 mm
/gate/source/F18LineSource2_11/gps/angtype iso
/gate/source/F18LineSource2_11/gps/radius 1.1 mm
/gate/source/F18LineSource2_11/gps/centre -18.630127018922195 -15.836791218280352 0.000000 mm

/gate/source/addSource F18LineSource2_12
/gate/source/F18LineSource2_12/setActivity 200000 Bq
/gate/source/F18LineSource2_12/setType backtoback
/gate/source/F18LineSource2_12/gps/particle gamma
/gate/source/F18LineSource2_12/gps/energytype Mono
/gate/source/F18LineSource2_12/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_12/gps/type Volume
/gate/source/F18LineSource2_12/gps/shape Cylinder
/gate/source/F18LineSource2_12/gps/halfz 40.0 mm
/gate/source/F18LineSource2_12/gps/angtype iso
/gate/source/F18LineSource2_12/gps/radius 1.1 mm
/gate/source/F18LineSource2_12/gps/centre -20.830127018922195 -12.026279441628821 0.000000 mm

/gate/source/addSource F18LineSource2_13
/gate/source/F18LineSource2_13/setActivity 200000 Bq
/gate/source/F18LineSource2_13/setType backtoback
/gate/source/F18LineSource2_13/gps/particle gamma
/gate/source/F18LineSource2_13/gps/energytype Mono
/gate/source/F18LineSource2_13/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_13/gps/type Volume
/gate/source/F18LineSource2_13/gps/shape Cylinder
/gate/source/F18LineSource2_13/gps/halfz 40.0 mm
/gate/source/F18LineSource2_13/gps/angtype iso
/gate/source/F18LineSource2_13/gps/radius 1.1 mm
/gate/source/F18LineSource2_13/gps/centre -23.030127018922194 -8.21576766497729 0.000000 mm

/gate/source/addSource F18LineSource2_14
/gate/source/F18LineSource2_14/setActivity 200000 Bq
/gate/source/F18LineSource2_14/setType backtoback
/gate/source/F18LineSource2_14/gps/particle gamma
/gate/source/F18LineSource2_14/gps/energytype Mono
/gate/source/F18LineSource2_14/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource2_14/gps/type Volume
/gate/source/F18LineSource2_14/gps/shape Cylinder
/gate/source/F18LineSource2_14/gps/halfz 40.0 mm
/gate/source/F18LineSource2_14/gps/angtype iso
/gate/source/F18LineSource2_14/gps/radius 1.1 mm
/gate/source/F18LineSource2_14/gps/centre -25.230127018922193 -4.40525588832576 0.000000 mm

########################## 1.8 mm #######################

/gate/source/addSource F18LineSource3_0
/gate/source/F18LineSource3_0/setActivity 200000 Bq
/gate/source/F18LineSource3_0/setType backtoback
/gate/source/F18LineSource3_0/gps/particle gamma
/gate/source/F18LineSource3_0/gps/energytype Mono
/gate/source/F18LineSource3_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_0/gps/type Volume
/gate/source/F18LineSource3_0/gps/shape Cylinder
/gate/source/F18LineSource3_0/gps/halfz 40.0 mm
/gate/source/F18LineSource3_0/gps/angtype iso
/gate/source/F18LineSource3_0/gps/radius 1.2 mm
/gate/source/F18LineSource3_0/gps/centre -1.1213995141616317e-15 -9.156921938165304 0.000000 mm

/gate/source/addSource F18LineSource3_1
/gate/source/F18LineSource3_1/setActivity 200000 Bq
/gate/source/F18LineSource3_1/setType backtoback
/gate/source/F18LineSource3_1/gps/particle gamma
/gate/source/F18LineSource3_1/gps/energytype Mono
/gate/source/F18LineSource3_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_1/gps/type Volume
/gate/source/F18LineSource3_1/gps/shape Cylinder
/gate/source/F18LineSource3_1/gps/halfz 40.0 mm
/gate/source/F18LineSource3_1/gps/angtype iso
/gate/source/F18LineSource3_1/gps/radius 1.2 mm
/gate/source/F18LineSource3_1/gps/centre 2.399999999999998 -13.31384387633061 0.000000 mm

/gate/source/addSource F18LineSource3_2
/gate/source/F18LineSource3_2/setActivity 200000 Bq
/gate/source/F18LineSource3_2/setType backtoback
/gate/source/F18LineSource3_2/gps/particle gamma
/gate/source/F18LineSource3_2/gps/energytype Mono
/gate/source/F18LineSource3_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_2/gps/type Volume
/gate/source/F18LineSource3_2/gps/shape Cylinder
/gate/source/F18LineSource3_2/gps/halfz 40.0 mm
/gate/source/F18LineSource3_2/gps/angtype iso
/gate/source/F18LineSource3_2/gps/radius 1.2 mm
/gate/source/F18LineSource3_2/gps/centre -2.4000000000000017 -13.31384387633061 0.000000 mm

/gate/source/addSource F18LineSource3_3
/gate/source/F18LineSource3_3/setActivity 200000 Bq
/gate/source/F18LineSource3_3/setType backtoback
/gate/source/F18LineSource3_3/gps/particle gamma
/gate/source/F18LineSource3_3/gps/energytype Mono
/gate/source/F18LineSource3_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_3/gps/type Volume
/gate/source/F18LineSource3_3/gps/shape Cylinder
/gate/source/F18LineSource3_3/gps/halfz 40.0 mm
/gate/source/F18LineSource3_3/gps/angtype iso
/gate/source/F18LineSource3_3/gps/radius 1.2 mm
/gate/source/F18LineSource3_3/gps/centre 4.799999999999998 -17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource3_4
/gate/source/F18LineSource3_4/setActivity 200000 Bq
/gate/source/F18LineSource3_4/setType backtoback
/gate/source/F18LineSource3_4/gps/particle gamma
/gate/source/F18LineSource3_4/gps/energytype Mono
/gate/source/F18LineSource3_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_4/gps/type Volume
/gate/source/F18LineSource3_4/gps/shape Cylinder
/gate/source/F18LineSource3_4/gps/halfz 40.0 mm
/gate/source/F18LineSource3_4/gps/angtype iso
/gate/source/F18LineSource3_4/gps/radius 1.2 mm
/gate/source/F18LineSource3_4/gps/centre -2.1395517433375426e-15 -17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource3_5
/gate/source/F18LineSource3_5/setActivity 200000 Bq
/gate/source/F18LineSource3_5/setType backtoback
/gate/source/F18LineSource3_5/gps/particle gamma
/gate/source/F18LineSource3_5/gps/energytype Mono
/gate/source/F18LineSource3_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_5/gps/type Volume
/gate/source/F18LineSource3_5/gps/shape Cylinder
/gate/source/F18LineSource3_5/gps/halfz 40.0 mm
/gate/source/F18LineSource3_5/gps/angtype iso
/gate/source/F18LineSource3_5/gps/radius 1.2 mm
/gate/source/F18LineSource3_5/gps/centre -4.800000000000002 -17.470765814495916 0.000000 mm

/gate/source/addSource F18LineSource3_6
/gate/source/F18LineSource3_6/setActivity 200000 Bq
/gate/source/F18LineSource3_6/setType backtoback
/gate/source/F18LineSource3_6/gps/particle gamma
/gate/source/F18LineSource3_6/gps/energytype Mono
/gate/source/F18LineSource3_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_6/gps/type Volume
/gate/source/F18LineSource3_6/gps/shape Cylinder
/gate/source/F18LineSource3_6/gps/halfz 40.0 mm
/gate/source/F18LineSource3_6/gps/angtype iso
/gate/source/F18LineSource3_6/gps/radius 1.2 mm
/gate/source/F18LineSource3_6/gps/centre 7.199999999999997 -21.62768775266122 0.000000 mm

/gate/source/addSource F18LineSource3_7
/gate/source/F18LineSource3_7/setActivity 200000 Bq
/gate/source/F18LineSource3_7/setType backtoback
/gate/source/F18LineSource3_7/gps/particle gamma
/gate/source/F18LineSource3_7/gps/energytype Mono
/gate/source/F18LineSource3_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_7/gps/type Volume
/gate/source/F18LineSource3_7/gps/shape Cylinder
/gate/source/F18LineSource3_7/gps/halfz 40.0 mm
/gate/source/F18LineSource3_7/gps/angtype iso
/gate/source/F18LineSource3_7/gps/radius 1.2 mm
/gate/source/F18LineSource3_7/gps/centre 2.399999999999997 -21.62768775266122 0.000000 mm

/gate/source/addSource F18LineSource3_8
/gate/source/F18LineSource3_8/setActivity 200000 Bq
/gate/source/F18LineSource3_8/setType backtoback
/gate/source/F18LineSource3_8/gps/particle gamma
/gate/source/F18LineSource3_8/gps/energytype Mono
/gate/source/F18LineSource3_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_8/gps/type Volume
/gate/source/F18LineSource3_8/gps/shape Cylinder
/gate/source/F18LineSource3_8/gps/halfz 40.0 mm
/gate/source/F18LineSource3_8/gps/angtype iso
/gate/source/F18LineSource3_8/gps/radius 1.2 mm
/gate/source/F18LineSource3_8/gps/centre -2.400000000000003 -21.62768775266122 0.000000 mm

/gate/source/addSource F18LineSource3_9
/gate/source/F18LineSource3_9/setActivity 200000 Bq
/gate/source/F18LineSource3_9/setType backtoback
/gate/source/F18LineSource3_9/gps/particle gamma
/gate/source/F18LineSource3_9/gps/energytype Mono
/gate/source/F18LineSource3_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource3_9/gps/type Volume
/gate/source/F18LineSource3_9/gps/shape Cylinder
/gate/source/F18LineSource3_9/gps/halfz 40.0 mm
/gate/source/F18LineSource3_9/gps/angtype iso
/gate/source/F18LineSource3_9/gps/radius 1.2 mm
/gate/source/F18LineSource3_9/gps/centre -7.200000000000002 -21.62768775266122 0.000000 mm

########################## 2.0 mm #######################

/gate/source/addSource F18LineSource4_0
/gate/source/F18LineSource4_0/setActivity 200000 Bq
/gate/source/F18LineSource4_0/setType backtoback
/gate/source/F18LineSource4_0/gps/particle gamma
/gate/source/F18LineSource4_0/gps/energytype Mono
/gate/source/F18LineSource4_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_0/gps/type Volume
/gate/source/F18LineSource4_0/gps/shape Cylinder
/gate/source/F18LineSource4_0/gps/halfz 40.0 mm
/gate/source/F18LineSource4_0/gps/angtype iso
/gate/source/F18LineSource4_0/gps/radius 1.3 mm
/gate/source/F18LineSource4_0/gps/centre 8.230127018922191 -4.751666049839545 0.000000 mm

/gate/source/addSource F18LineSource4_1
/gate/source/F18LineSource4_1/setActivity 200000 Bq
/gate/source/F18LineSource4_1/setType backtoback
/gate/source/F18LineSource4_1/gps/particle gamma
/gate/source/F18LineSource4_1/gps/energytype Mono
/gate/source/F18LineSource4_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_1/gps/type Volume
/gate/source/F18LineSource4_1/gps/shape Cylinder
/gate/source/F18LineSource4_1/gps/halfz 40.0 mm
/gate/source/F18LineSource4_1/gps/angtype iso
/gate/source/F18LineSource4_1/gps/radius 1.3 mm
/gate/source/F18LineSource4_1/gps/centre 13.430127018922189 -4.751666049839547 0.000000 mm

/gate/source/addSource F18LineSource4_2
/gate/source/F18LineSource4_2/setActivity 200000 Bq
/gate/source/F18LineSource4_2/setType backtoback
/gate/source/F18LineSource4_2/gps/particle gamma
/gate/source/F18LineSource4_2/gps/energytype Mono
/gate/source/F18LineSource4_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_2/gps/type Volume
/gate/source/F18LineSource4_2/gps/shape Cylinder
/gate/source/F18LineSource4_2/gps/halfz 40.0 mm
/gate/source/F18LineSource4_2/gps/angtype iso
/gate/source/F18LineSource4_2/gps/radius 1.3 mm
/gate/source/F18LineSource4_2/gps/centre 10.830127018922187 -9.254998149518627 0.000000 mm

/gate/source/addSource F18LineSource4_3
/gate/source/F18LineSource4_3/setActivity 200000 Bq
/gate/source/F18LineSource4_3/setType backtoback
/gate/source/F18LineSource4_3/gps/particle gamma
/gate/source/F18LineSource4_3/gps/energytype Mono
/gate/source/F18LineSource4_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_3/gps/type Volume
/gate/source/F18LineSource4_3/gps/shape Cylinder
/gate/source/F18LineSource4_3/gps/halfz 40.0 mm
/gate/source/F18LineSource4_3/gps/angtype iso
/gate/source/F18LineSource4_3/gps/radius 1.3 mm
/gate/source/F18LineSource4_3/gps/centre 18.630127018922188 -4.7516660498395495 0.000000 mm

/gate/source/addSource F18LineSource4_4
/gate/source/F18LineSource4_4/setActivity 200000 Bq
/gate/source/F18LineSource4_4/setType backtoback
/gate/source/F18LineSource4_4/gps/particle gamma
/gate/source/F18LineSource4_4/gps/energytype Mono
/gate/source/F18LineSource4_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_4/gps/type Volume
/gate/source/F18LineSource4_4/gps/shape Cylinder
/gate/source/F18LineSource4_4/gps/halfz 40.0 mm
/gate/source/F18LineSource4_4/gps/angtype iso
/gate/source/F18LineSource4_4/gps/radius 1.3 mm
/gate/source/F18LineSource4_4/gps/centre 16.030127018922187 -9.254998149518629 0.000000 mm

/gate/source/addSource F18LineSource4_5
/gate/source/F18LineSource4_5/setActivity 200000 Bq
/gate/source/F18LineSource4_5/setType backtoback
/gate/source/F18LineSource4_5/gps/particle gamma
/gate/source/F18LineSource4_5/gps/energytype Mono
/gate/source/F18LineSource4_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_5/gps/type Volume
/gate/source/F18LineSource4_5/gps/shape Cylinder
/gate/source/F18LineSource4_5/gps/halfz 40.0 mm
/gate/source/F18LineSource4_5/gps/angtype iso
/gate/source/F18LineSource4_5/gps/radius 1.3 mm
/gate/source/F18LineSource4_5/gps/centre 13.430127018922185 -13.758330249197709 0.000000 mm

/gate/source/addSource F18LineSource4_6
/gate/source/F18LineSource4_6/setActivity 200000 Bq
/gate/source/F18LineSource4_6/setType backtoback
/gate/source/F18LineSource4_6/gps/particle gamma
/gate/source/F18LineSource4_6/gps/energytype Mono
/gate/source/F18LineSource4_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_6/gps/type Volume
/gate/source/F18LineSource4_6/gps/shape Cylinder
/gate/source/F18LineSource4_6/gps/halfz 40.0 mm
/gate/source/F18LineSource4_6/gps/angtype iso
/gate/source/F18LineSource4_6/gps/radius 1.3 mm
/gate/source/F18LineSource4_6/gps/centre 23.83012701892219 -4.751666049839551 0.000000 mm

/gate/source/addSource F18LineSource4_7
/gate/source/F18LineSource4_7/setActivity 200000 Bq
/gate/source/F18LineSource4_7/setType backtoback
/gate/source/F18LineSource4_7/gps/particle gamma
/gate/source/F18LineSource4_7/gps/energytype Mono
/gate/source/F18LineSource4_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_7/gps/type Volume
/gate/source/F18LineSource4_7/gps/shape Cylinder
/gate/source/F18LineSource4_7/gps/halfz 40.0 mm
/gate/source/F18LineSource4_7/gps/angtype iso
/gate/source/F18LineSource4_7/gps/radius 1.3 mm
/gate/source/F18LineSource4_7/gps/centre 21.230127018922186 -9.25499814951863 0.000000 mm

/gate/source/addSource F18LineSource4_8
/gate/source/F18LineSource4_8/setActivity 200000 Bq
/gate/source/F18LineSource4_8/setType backtoback
/gate/source/F18LineSource4_8/gps/particle gamma
/gate/source/F18LineSource4_8/gps/energytype Mono
/gate/source/F18LineSource4_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_8/gps/type Volume
/gate/source/F18LineSource4_8/gps/shape Cylinder
/gate/source/F18LineSource4_8/gps/halfz 40.0 mm
/gate/source/F18LineSource4_8/gps/angtype iso
/gate/source/F18LineSource4_8/gps/radius 1.3 mm
/gate/source/F18LineSource4_8/gps/centre 18.630127018922185 -13.75833024919771 0.000000 mm

/gate/source/addSource F18LineSource4_9
/gate/source/F18LineSource4_9/setActivity 200000 Bq
/gate/source/F18LineSource4_9/setType backtoback
/gate/source/F18LineSource4_9/gps/particle gamma
/gate/source/F18LineSource4_9/gps/energytype Mono
/gate/source/F18LineSource4_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource4_9/gps/type Volume
/gate/source/F18LineSource4_9/gps/shape Cylinder
/gate/source/F18LineSource4_9/gps/halfz 40.0 mm
/gate/source/F18LineSource4_9/gps/angtype iso
/gate/source/F18LineSource4_9/gps/radius 1.3 mm
/gate/source/F18LineSource4_9/gps/centre 16.03012701892218 -18.26166234887679 0.000000 mm

########################## 2.2 mm #######################

/gate/source/addSource F18LineSource5_0
/gate/source/F18LineSource5_0/setActivity 200000 Bq
/gate/source/F18LineSource5_0/setType backtoback
/gate/source/F18LineSource5_0/gps/particle gamma
/gate/source/F18LineSource5_0/gps/energytype Mono
/gate/source/F18LineSource5_0/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_0/gps/type Volume
/gate/source/F18LineSource5_0/gps/shape Cylinder
/gate/source/F18LineSource5_0/gps/halfz 40.0 mm
/gate/source/F18LineSource5_0/gps/angtype iso
/gate/source/F18LineSource5_0/gps/radius 1.4 mm
/gate/source/F18LineSource5_0/gps/centre 8.530127018922192 4.924871130596428 0.000000 mm

/gate/source/addSource F18LineSource5_1
/gate/source/F18LineSource5_1/setActivity 200000 Bq
/gate/source/F18LineSource5_1/setType backtoback
/gate/source/F18LineSource5_1/gps/particle gamma
/gate/source/F18LineSource5_1/gps/energytype Mono
/gate/source/F18LineSource5_1/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_1/gps/type Volume
/gate/source/F18LineSource5_1/gps/shape Cylinder
/gate/source/F18LineSource5_1/gps/halfz 40.0 mm
/gate/source/F18LineSource5_1/gps/angtype iso
/gate/source/F18LineSource5_1/gps/radius 1.4 mm
/gate/source/F18LineSource5_1/gps/centre 11.330127018922191 9.774613391789286 0.000000 mm

/gate/source/addSource F18LineSource5_2
/gate/source/F18LineSource5_2/setActivity 200000 Bq
/gate/source/F18LineSource5_2/setType backtoback
/gate/source/F18LineSource5_2/gps/particle gamma
/gate/source/F18LineSource5_2/gps/energytype Mono
/gate/source/F18LineSource5_2/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_2/gps/type Volume
/gate/source/F18LineSource5_2/gps/shape Cylinder
/gate/source/F18LineSource5_2/gps/halfz 40.0 mm
/gate/source/F18LineSource5_2/gps/angtype iso
/gate/source/F18LineSource5_2/gps/radius 1.4 mm
/gate/source/F18LineSource5_2/gps/centre 14.130127018922192 4.924871130596429 0.000000 mm

/gate/source/addSource F18LineSource5_3
/gate/source/F18LineSource5_3/setActivity 200000 Bq
/gate/source/F18LineSource5_3/setType backtoback
/gate/source/F18LineSource5_3/gps/particle gamma
/gate/source/F18LineSource5_3/gps/energytype Mono
/gate/source/F18LineSource5_3/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_3/gps/type Volume
/gate/source/F18LineSource5_3/gps/shape Cylinder
/gate/source/F18LineSource5_3/gps/halfz 40.0 mm
/gate/source/F18LineSource5_3/gps/angtype iso
/gate/source/F18LineSource5_3/gps/radius 1.4 mm
/gate/source/F18LineSource5_3/gps/centre 14.130127018922192 14.624355652982143 0.000000 mm

/gate/source/addSource F18LineSource5_4
/gate/source/F18LineSource5_4/setActivity 200000 Bq
/gate/source/F18LineSource5_4/setType backtoback
/gate/source/F18LineSource5_4/gps/particle gamma
/gate/source/F18LineSource5_4/gps/energytype Mono
/gate/source/F18LineSource5_4/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_4/gps/type Volume
/gate/source/F18LineSource5_4/gps/shape Cylinder
/gate/source/F18LineSource5_4/gps/halfz 40.0 mm
/gate/source/F18LineSource5_4/gps/angtype iso
/gate/source/F18LineSource5_4/gps/radius 1.4 mm
/gate/source/F18LineSource5_4/gps/centre 16.930127018922192 9.774613391789286 0.000000 mm

/gate/source/addSource F18LineSource5_5
/gate/source/F18LineSource5_5/setActivity 200000 Bq
/gate/source/F18LineSource5_5/setType backtoback
/gate/source/F18LineSource5_5/gps/particle gamma
/gate/source/F18LineSource5_5/gps/energytype Mono
/gate/source/F18LineSource5_5/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_5/gps/type Volume
/gate/source/F18LineSource5_5/gps/shape Cylinder
/gate/source/F18LineSource5_5/gps/halfz 40.0 mm
/gate/source/F18LineSource5_5/gps/angtype iso
/gate/source/F18LineSource5_5/gps/radius 1.4 mm
/gate/source/F18LineSource5_5/gps/centre 19.730127018922193 4.92487113059643 0.000000 mm

/gate/source/addSource F18LineSource5_6
/gate/source/F18LineSource5_6/setActivity 200000 Bq
/gate/source/F18LineSource5_6/setType backtoback
/gate/source/F18LineSource5_6/gps/particle gamma
/gate/source/F18LineSource5_6/gps/energytype Mono
/gate/source/F18LineSource5_6/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_6/gps/type Volume
/gate/source/F18LineSource5_6/gps/shape Cylinder
/gate/source/F18LineSource5_6/gps/halfz 40.0 mm
/gate/source/F18LineSource5_6/gps/angtype iso
/gate/source/F18LineSource5_6/gps/radius 1.4 mm
/gate/source/F18LineSource5_6/gps/centre 16.93012701892219 19.474097914174997 0.000000 mm

/gate/source/addSource F18LineSource5_7
/gate/source/F18LineSource5_7/setActivity 200000 Bq
/gate/source/F18LineSource5_7/setType backtoback
/gate/source/F18LineSource5_7/gps/particle gamma
/gate/source/F18LineSource5_7/gps/energytype Mono
/gate/source/F18LineSource5_7/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_7/gps/type Volume
/gate/source/F18LineSource5_7/gps/shape Cylinder
/gate/source/F18LineSource5_7/gps/halfz 40.0 mm
/gate/source/F18LineSource5_7/gps/angtype iso
/gate/source/F18LineSource5_7/gps/radius 1.4 mm
/gate/source/F18LineSource5_7/gps/centre 19.73012701892219 14.624355652982143 0.000000 mm

/gate/source/addSource F18LineSource5_8
/gate/source/F18LineSource5_8/setActivity 200000 Bq
/gate/source/F18LineSource5_8/setType backtoback
/gate/source/F18LineSource5_8/gps/particle gamma
/gate/source/F18LineSource5_8/gps/energytype Mono
/gate/source/F18LineSource5_8/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_8/gps/type Volume
/gate/source/F18LineSource5_8/gps/shape Cylinder
/gate/source/F18LineSource5_8/gps/halfz 40.0 mm
/gate/source/F18LineSource5_8/gps/angtype iso
/gate/source/F18LineSource5_8/gps/radius 1.4 mm
/gate/source/F18LineSource5_8/gps/centre 22.53012701892219 9.774613391789286 0.000000 mm

/gate/source/addSource F18LineSource5_9
/gate/source/F18LineSource5_9/setActivity 200000 Bq
/gate/source/F18LineSource5_9/setType backtoback
/gate/source/F18LineSource5_9/gps/particle gamma
/gate/source/F18LineSource5_9/gps/energytype Mono
/gate/source/F18LineSource5_9/gps/monoenergy 0.511 MeV
/gate/source/F18LineSource5_9/gps/type Volume
/gate/source/F18LineSource5_9/gps/shape Cylinder
/gate/source/F18LineSource5_9/gps/halfz 40.0 mm
/gate/source/F18LineSource5_9/gps/angtype iso
/gate/source/F18LineSource5_9/gps/radius 1.4 mm
/gate/source/F18LineSource5_9/gps/centre 25.330127018922187 4.924871130596432 0.000000 mm

