#	D I G I T I Z E R 
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert adderCompton
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/readout/setPolicy TakeEnergyCentroid
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/readout/setDepth 4

#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert crosstalk
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/crosstalk/chooseCrosstalkVolume crystal
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/crosstalk/setEdgesFraction 0.05
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/crosstalk/setCornersFraction 0.05

# GEN 2 Specific energy resolution of 11.6%
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/fwhm 0.116
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMin 450. keV
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMin 10. keV
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMin 452. keV

#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMax 1200. keV
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMax 600. keV

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert timeResolution
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/timeResolution/fwhm 250 ps

#/gate/digitizerMgr/crystal/SinglesDigitizer/LYSO/SinglesDigitizer/Singles/insert pileup
#/gate/digitizerMgr/crystal/SinglesDigitizer/LYSO/SinglesDigitizer/Singles/pileup/setDepth 4 # to set depth
#/gate/digitizerMgr/crystal/SinglesDigitizer/LYSO/SinglesDigitizer/Singles/pileup/setPileup 10 ns


#/gate/distributions/name energy_distrib
#/gate/distributions/insert Gaussian
#/gate/distributions/energy_distrib/setMean 120 keV
#/gate/distributions/energy_distrib/setSigma 30 keV

#/gate/distributions/name dt_distrib
#/gate/distributions/insert Gaussian
#/gate/distributions/energy_distrib/setMean 0 ps
#/gate/distributions/energy_distrib/setSigma 105 ps

#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert noise
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/noise/setDeltaTDistribution dt_distrib
#/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/noise/setEnergyDistribution energy_distrib



#	C O I N C I    S O R T E R 
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow 4800 ps
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy  takeWinnerOfGoods
/gate/digitizerMgr/CoincidenceSorter/Coincidences/minSectorDifference 1

/gate/digitizerMgr/name delay
/gate/digitizerMgr/insert CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow 4800. ps
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset 100. ns
#/gate/digitizerMgr/CoincidenceSorter/delay/minSectorDifference 1
#/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy  takeWinnerOfGoods

#energy452-590
