/gate/source/addSource Background

/gate/source/Background/setActivity 1.5 mCi
/gate/source/Background/gps/particle gamma
/gate/source/Background/gps/energytype Mono
/gate/source/Background/setType backtoback
/gate/source/Background/gps/type Volume
/gate/source/Background/gps/shape Cylinder
/gate/source/Background/gps/radius 104.5 mm
# halfz is (186 mm - 88 mm) / 2 = 49
/gate/source/Background/gps/halfz 49. mm
# z coord is 19.05 mm - 49 mm = -29.95 mm
/gate/source/Background/gps/centre 0 0 -29.95 mm
/gate/source/Background/gps/monoenergy 0.511 MeV
/gate/source/Background/gps/angtype iso


/gate/source/addSource LidA

/gate/source/LidA/setActivity 3.451 muCi
/gate/source/LidA/setType backtoback
/gate/source/LidA/gps/particle gamma
/gate/source/LidA/gps/energytype Mono
/gate/source/LidA/gps/monoenergy 0.511 MeV
/gate/source/LidA/gps/angtype iso

/gate/source/LidA/gps/type Volume
/gate/source/LidA/gps/shape Cylinder
/gate/source/LidA/gps/radius 4. mm
/gate/source/LidA/gps/halfz 19.05 mm

/gate/source/LidA/gps/centre -17.062 56.774 0 mm



/gate/source/addSource LidB

/gate/source/LidB/setActivity 7.765 muCi
/gate/source/LidB/setType backtoback
/gate/source/LidB/gps/particle gamma
/gate/source/LidB/gps/energytype Mono
/gate/source/LidB/gps/monoenergy 0.511 MeV
/gate/source/LidB/gps/angtype iso

/gate/source/LidB/gps/type Volume
/gate/source/LidB/gps/shape Cylinder
/gate/source/LidB/gps/radius 6. mm
/gate/source/LidB/gps/halfz 19.05 mm

/gate/source/LidB/gps/centre 9.855 57.803 0 mm



/gate/source/addSource LidC

/gate/source/LidC/setActivity 13.805 muCi
/gate/source/LidC/setType backtoback
/gate/source/LidC/gps/particle gamma
/gate/source/LidC/gps/energytype Mono
/gate/source/LidC/gps/monoenergy 0.511 MeV
/gate/source/LidC/gps/angtype iso

/gate/source/LidC/gps/type Volume
/gate/source/LidC/gps/shape Cylinder
/gate/source/LidC/gps/radius 8. mm
/gate/source/LidC/gps/halfz 19.05 mm

/gate/source/LidC/gps/centre 38.241 40.301 0 mm


/gate/source/addSource LidD

/gate/source/LidD/setActivity 33.703 muCi
/gate/source/LidD/setType backtoback
/gate/source/LidD/gps/particle gamma
/gate/source/LidD/gps/energytype Mono
/gate/source/LidD/gps/monoenergy 0.511 MeV
/gate/source/LidD/gps/angtype iso

/gate/source/LidD/gps/type Volume
/gate/source/LidD/gps/shape Cylinder
/gate/source/LidD/gps/radius 12.5 mm
/gate/source/LidD/gps/halfz 19.05 mm

/gate/source/LidD/gps/centre 52.067 -7.648 0 mm


/gate/source/Background/gps/Forbid cold_area1
/gate/source/Background/gps/Forbid cold_area2
/gate/source/Background/gps/Forbid cold_area3
/gate/source/Background/gps/Forbid cold_area4
/gate/source/Background/gps/Forbid cold_bone
/gate/source/Background/gps/Forbid cold_water
/gate/source/Background/gps/Forbid cold_air
