/gate/world/daughters/name bgcyl
/gate/world/daughters/insert cylinder
/gate/bgcyl/vis/setColor magenta
/gate/bgcyl/geometry/setRmax 110.9 mm
/gate/bgcyl/geometry/setHeight 186 mm
/gate/bgcyl/setMaterial Water
/gate/bgcyl/placement/setTranslation  0 0 -29.95 mm
/gate/bgcyl/vis/forceWireframe


/gate/bgcyl/daughters/name cold_area1
/gate/bgcyl/daughters/insert cylinder
/gate/cold_area1/vis/setColor green
/gate/cold_area1/geometry/setRmax 4. mm
/gate/cold_area1/geometry/setHeight 38.1 mm
/gate/cold_area1/setMaterial Water
/gate/cold_area1/placement/setTranslation  -17.062 56.774 29.95 mm
/gate/cold_area1/vis/forceSolid

/gate/bgcyl/daughters/name cold_area2
/gate/bgcyl/daughters/insert cylinder
/gate/cold_area2/vis/setColor green
/gate/cold_area2/geometry/setRmax 6. mm
/gate/cold_area2/geometry/setHeight 38.1 mm
/gate/cold_area2/setMaterial Water
/gate/cold_area2/placement/setTranslation  9.855 57.803 29.95 mm
/gate/cold_area2/vis/forceSolid

/gate/bgcyl/daughters/name cold_area3
/gate/bgcyl/daughters/insert cylinder
/gate/cold_area3/vis/setColor green
/gate/cold_area3/geometry/setRmax 8. mm
/gate/cold_area3/geometry/setHeight 38.1 mm
/gate/cold_area3/setMaterial Water
/gate/cold_area3/placement/setTranslation  38.241 40.301 29.95 mm
/gate/cold_area3/vis/forceSolid

/gate/bgcyl/daughters/name cold_area4
/gate/bgcyl/daughters/insert cylinder
/gate/cold_area4/vis/setColor green
/gate/cold_area4/geometry/setRmax 12.5 mm
/gate/cold_area4/geometry/setHeight 38.1 mm
/gate/cold_area4/setMaterial Water
/gate/cold_area4/placement/setTranslation  52.067 -7.648 29.95 mm
/gate/cold_area4/vis/forceSolid


/gate/bgcyl/daughters/name cold_bone
/gate/bgcyl/daughters/insert cylinder
/gate/cold_bone/vis/setColor green
/gate/cold_bone/geometry/setRmax 12.5 mm
/gate/cold_bone/geometry/setHeight 38.1 mm
/gate/cold_bone/setMaterial Teflon
/gate/cold_bone/placement/setTranslation  21.180 -50.890 29.95 mm
/gate/cold_bone/vis/forceSolid

/gate/bgcyl/daughters/name cold_air
/gate/bgcyl/daughters/insert cylinder
/gate/cold_air/vis/setColor green
/gate/cold_air/geometry/setRmax 12.5 mm
/gate/cold_air/geometry/setHeight 38.1 mm
/gate/cold_air/setMaterial Air
/gate/cold_air/placement/setTranslation  -34.417 -45.301 29.95 mm
/gate/cold_air/vis/forceSolid

/gate/bgcyl/daughters/name cold_water
/gate/bgcyl/daughters/insert cylinder
/gate/cold_water/vis/setColor green
/gate/cold_water/geometry/setRmax 12.5 mm
/gate/cold_water/geometry/setHeight 38.1 mm
/gate/cold_water/setMaterial Water
/gate/cold_water/placement/setTranslation  -60.304 3.824 29.95 mm
/gate/cold_water/vis/forceSolid