/gate/source/addSource CYLINDER

/gate/source/CYLINDER/setActivity 1.5 mCi
/gate/source/CYLINDER/setType backtoback
/gate/source/CYLINDER/gps/particle gamma
/gate/source/CYLINDER/gps/energytype Mono
/gate/source/CYLINDER/gps/monoenergy 0.511 MeV


/gate/source/CYLINDER/gps/angtype iso

/gate/source/CYLINDER/gps/type Volume

/gate/source/CYLINDER/gps/shape Cylinder
/gate/source/CYLINDER/gps/radius 120 mm
/gate/source/CYLINDER/gps/halfz 100 mm

/gate/source/CYLINDER/gps/centre 0. 0. 0. cm

/gate/world/daughters/name bgcyl
/gate/world/daughters/insert cylinder
/gate/bgcyl/vis/setColor magenta
/gate/bgcyl/geometry/setRmax 120 mm
/gate/bgcyl/geometry/setHeight 200 mm
/gate/bgcyl/setMaterial Water
/gate/bgcyl/placement/setTranslation  0 0 0 mm
/gate/bgcyl/vis/forceWireframe