#
#       P H Y S I C S
#

# general

/gate/physics/addProcess OpticalAbsorption
/gate/physics/addProcess OpticalRayleigh
/gate/physics/addProcess OpticalBoundary
/gate/physics/addProcess OpticalMie
/gate/physics/addProcess OpticalWLS
/gate/physics/addProcess Scintillation


/gate/physics/addProcess PhotoElectric gamma
/gate/physics/processes/PhotoElectric/setModel StandardModel

#/gate/physics/addProcess Compton gamma
#/gate/physics/processes/Compton/setModel StandardModel

#/gate/physics/addProcess RayleighScattering gamma
#/gate/physics/processes/RayleighScattering/setModel PenelopeModel

/gate/physics/addProcess GammaConversion gamma
/gate/physics/processes/GammaConversion/setModel StandardModel

/gate/physics/addProcess ElectronIonisation
/gate/physics/processes/ElectronIonisation/setModel StandardModel e-
/gate/physics/processes/ElectronIonisation/setModel StandardModel e+

/gate/physics/addProcess Bremsstrahlung
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
/gate/physics/processes/Bremsstrahlung/setModel StandardModel e+


/gate/physics/addProcess PositronAnnihilation

#/gate/physics/addProcess eMultipleScattering e-
#/gate/physics/addProcess eMultipleScattering e+


/gate/physics/addProcess RadioactiveDecay

/gate/physics/processList Enabled
/gate/physics/processList Initialized

#
#       C U T S
#


# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      NEMACylinder 1.0 cm

#/gate/physics/Electron/SetCutInRegion   NEMACylinder 1.0 cm
#/gate/physics/Positron/SetCutInRegion   NEMACylinder 1.0 cm

# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      layer0 1.0 cm
#/gate/physics/Electron/SetCutInRegion   layer0 1.0 cm
#/gate/physics/Positron/SetCutInRegion   layer0 1.0 cm


