/gate/source/addSource LINE

/gate/source/LINE/setActivity 1.5 mCi
/gate/source/LINE/setType backtoback
/gate/source/LINE/gps/particle gamma
/gate/source/LINE/gps/energytype Mono
/gate/source/LINE/gps/monoenergy 0.511 MeV


/gate/source/LINE/gps/angtype iso

/gate/source/LINE/gps/type Volume

/gate/source/LINE/gps/shape LINE
/gate/source/LINE/gps/radius 3 mm
/gate/source/LINE/gps/halfz 350 mm

/gate/source/LINE/gps/centre 4.5 0. 0. cm
