/vis/enable
/vis/open OGL

/gate/geometry/setMaterialDatabase ./GateMaterials.db


/gate/world/geometry/setXLength       400. cm
/gate/world/geometry/setYLength       400. cm
/gate/world/geometry/setZLength       400. cm

/gate/run/initialize

/control/execute sourcesNorm.mac

/vis/scene/create

/vis/sceneHandler/attach scene-0

/control/execute Geometry.mac

/gate/run/initialize

/vis/drawVolume

/gate/source/AnnulusSource/visualize 5000 red 2
